# Generated by Django 5.2.1 on 2025-06-02 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subtipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtipos', to='ProjetoEstoque.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('numero_serie', models.CharField(max_length=100, unique=True)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('local', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('backup', 'Backup'), ('correcao', 'Correção'), ('manutencao', 'Manutenção'), ('queimado', 'Queimado')], default='ativo', max_length=20)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('estoque_minimo', models.PositiveIntegerField(default=0)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ProjetoEstoque.categoria')),
                ('subtipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ProjetoEstoque.subtipo')),
            ],
        ),
    ]
