# Generated by Django 5.2.1 on 2025-08-21 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locacao',
            options={},
        ),
        migrations.AlterField(
            model_name='locacao',
            name='contrato',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='equipamento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='locacao', to='ProjetoEstoque.item'),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='tempo_locado',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
