# Generated by Django 5.2.1 on 2025-08-21 19:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0002_alter_locacao_options_alter_locacao_contrato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locacao',
            name='valor_mensal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor do pagamento mensal (R$)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='tempo_locado',
            field=models.IntegerField(blank=True, help_text='Informe a quantidade de meses', null=True),
        ),
    ]
