# Generated by Django 5.2.1 on 2025-08-21 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0003_locacao_valor_mensal_alter_locacao_tempo_locado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimentacaoitem',
            options={'ordering': ['-created_at'], 'verbose_name': 'Movimentação de Item', 'verbose_name_plural': 'Movimentações de Itens'},
        ),
        migrations.RemoveField(
            model_name='movimentacaoitem',
            name='centro_custo',
        ),
        migrations.RemoveField(
            model_name='movimentacaoitem',
            name='localidade',
        ),
        migrations.AddField(
            model_name='movimentacaoitem',
            name='centro_custo_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movs_destino', to='ProjetoEstoque.centrocusto'),
        ),
        migrations.AddField(
            model_name='movimentacaoitem',
            name='centro_custo_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movs_origem', to='ProjetoEstoque.centrocusto'),
        ),
        migrations.AddField(
            model_name='movimentacaoitem',
            name='localidade_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movs_destino', to='ProjetoEstoque.localidade'),
        ),
        migrations.AddField(
            model_name='movimentacaoitem',
            name='localidade_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movs_origem', to='ProjetoEstoque.localidade'),
        ),
        migrations.AddField(
            model_name='movimentacaoitem',
            name='status_retorno',
            field=models.CharField(blank=True, choices=[('ativo', 'Ativo'), ('backup', 'Backup'), ('manutencao', 'Manutenção'), ('defeito', 'Defeito'), ('pausado', 'Pausado')], help_text='Status do item após retorno da manutenção (Ativo ou Backup)', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='movimentacaoitem',
            name='chamado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movimentacaoitem',
            name='custo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='movimentacaoitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='ProjetoEstoque.item'),
        ),
        migrations.AlterField(
            model_name='movimentacaoitem',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='movimentacaoitem',
            name='tipo_movimentacao',
            field=models.CharField(choices=[('transferencia', 'Transferência'), ('baixa', 'Baixa'), ('entrada', 'Entrada'), ('envio_manutencao', 'Envio para Manutenção'), ('retorno_manutencao', 'Retorno de Manutenção'), ('outros', 'Outros')], max_length=30),
        ),
        migrations.AlterField(
            model_name='movimentacaoitem',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes', to='ProjetoEstoque.usuario'),
        ),
    ]
