# Generated by Django 5.2.1 on 2025-06-06 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0004_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='periodicidade_preventiva',
            field=models.PositiveIntegerField(default=6, help_text='Número de meses para calcular a próxima preventiva', verbose_name='Periodicidade preventiva (meses)'),
        ),
        migrations.CreateModel(
            name='Preventiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ultima_preventiva', models.DateField(editable=False)),
                ('data_proxima', models.DateField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preventivas', to='ProjetoEstoque.equipamento')),
            ],
        ),
    ]
