# Generated by Django 5.2.1 on 2025-08-22 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0004_alter_movimentacaoitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='centro_custo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProjetoEstoque.centrocusto'),
        ),
    ]
