# Generated by Django 5.2.1 on 2025-08-25 19:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0005_item_centro_custo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaoitem',
            name='centro_custo_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movs_destino_cc', to='ProjetoEstoque.centrocusto'),
        ),
        migrations.AlterField(
            model_name='movimentacaoitem',
            name='centro_custo_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movs_origem_cc', to='ProjetoEstoque.centrocusto'),
        ),
        migrations.AlterField(
            model_name='movimentacaoitem',
            name='localidade_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movs_destino_loc', to='ProjetoEstoque.localidade'),
        ),
        migrations.AlterField(
            model_name='movimentacaoitem',
            name='localidade_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movs_origem_loc', to='ProjetoEstoque.localidade'),
        ),
        migrations.AlterField(
            model_name='movimentacaoitem',
            name='quantidade',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
