# Generated by Django 5.2.1 on 2025-06-06 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0005_equipamento_periodicidade_preventiva_preventiva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamento',
            name='atualizado_por',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='periodicidade_preventiva',
        ),
        migrations.AddField(
            model_name='equipamento',
            name='data_limite_preventiva',
            field=models.PositiveIntegerField(blank=True, help_text='Intervalo (em meses) para próxima preventiva', null=True),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='precisa_preventiva',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('backup', 'Backup'), ('correcao', 'Correção'), ('manutencao', 'Manutenção'), ('queimado', 'Queimado')], default='ativo', max_length=20),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='subtipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ProjetoEstoque.subtipo'),
        ),
    ]
