# Generated by Django 5.2.1 on 2025-08-26 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0006_alter_movimentacaoitem_centro_custo_destino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaoitem',
            name='tipo_transferencia',
            field=models.CharField(blank=True, choices=[('entrega', 'Entrega'), ('devolucao', 'Devolução')], help_text='Usado somente quando tipo_movimentacao = Transferência.', max_length=15, null=True),
        ),
    ]
