# Generated by Django 5.2.1 on 2025-06-06 16:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0007_rename_observacao_preventiva_observacoes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preventiva',
            old_name='usuario',
            new_name='autor',
        ),
        migrations.RemoveField(
            model_name='preventiva',
            name='data_anterior',
        ),
        migrations.AlterField(
            model_name='preventiva',
            name='data_proxima',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='preventiva',
            name='data_ultima',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='preventiva',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
    ]
