# Generated by Django 5.2.1 on 2025-08-27 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0007_movimentacaoitem_tipo_transferencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='centrocusto',
            name='pmb',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', help_text='Centro de custo pertence ao PMB?', max_length=3),
        ),
        migrations.AddField(
            model_name='movimentacaoitem',
            name='fornecedor_manutencao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manutencoes', to='ProjetoEstoque.fornecedor'),
        ),
        migrations.AlterField(
            model_name='movimentacaoitem',
            name='centro_custo_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movs_destino', to='ProjetoEstoque.centrocusto'),
        ),
        migrations.AlterField(
            model_name='movimentacaoitem',
            name='centro_custo_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movs_origem', to='ProjetoEstoque.centrocusto'),
        ),
        migrations.AlterField(
            model_name='movimentacaoitem',
            name='localidade_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movs_destino', to='ProjetoEstoque.localidade'),
        ),
        migrations.AlterField(
            model_name='movimentacaoitem',
            name='localidade_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movs_origem', to='ProjetoEstoque.localidade'),
        ),
        migrations.AlterField(
            model_name='movimentacaoitem',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='movimentacaoitem',
            name='status_retorno',
            field=models.CharField(blank=True, choices=[('ativo', 'Ativo'), ('backup', 'Backup'), ('manutencao', 'Manutenção'), ('defeito', 'Defeito'), ('pausado', 'Pausado')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='movimentacaoitem',
            name='tipo_transferencia',
            field=models.CharField(blank=True, choices=[('entrega', 'Entrega'), ('devolucao', 'Devolução')], help_text='Somente para transferência.', max_length=10, null=True),
        ),
    ]
