# Generated by Django 5.2.1 on 2025-08-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0008_centrocusto_pmb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='localidade',
            name='codigo',
            field=models.CharField(blank=True, choices=[('karitel', 'Karitel'), ('rio_do_meio', 'Rio do Meio')], help_text='Sede: ', max_length=20, null=True, unique=True),
        ),
    ]
