# Generated by Django 5.2.1 on 2025-06-07 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0008_rename_usuario_preventiva_autor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventiva',
            name='realizada_dentro_prazo',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3),
        ),
        migrations.AlterField(
            model_name='preventiva',
            name='data_proxima',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='preventiva',
            name='data_ultima',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='preventiva',
            name='equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjetoEstoque.equipamento'),
        ),
    ]
