# Generated by Django 5.2.1 on 2025-06-07 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0009_preventiva_realizada_dentro_prazo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='preventiva',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='preventiva',
            name='data_ultima',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='preventiva',
            name='realizada_dentro_prazo',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=10),
        ),
    ]
