# Generated by Django 5.2.1 on 2025-08-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0009_localidade_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localidade',
            name='codigo',
            field=models.CharField(blank=True, choices=[('karitel', 'Karitel'), ('Rio_do_Meio', 'Rio do Meio')], help_text='Sede: ', max_length=20, null=True),
        ),
    ]
