# Generated by Django 5.2.1 on 2025-06-07 19:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0010_alter_preventiva_autor_alter_preventiva_data_ultima_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preventiva',
            name='realizada_dentro_prazo',
        ),
        migrations.AddField(
            model_name='preventiva',
            name='dentro_do_prazo',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3),
        ),
        migrations.AlterField(
            model_name='preventiva',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='preventiva',
            name='data_proxima',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preventiva',
            name='data_ultima',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='preventiva',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
