# Generated by Django 5.2.1 on 2025-09-01 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0010_alter_localidade_codigo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckListModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=120)),
                ('ativo', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='sim', max_length=3)),
                ('intervalo_dias', models.PositiveIntegerField(default=0, help_text='Periodicidade padrão (dias). 0 = sem programação.')),
                ('atualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizador', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criador', to=settings.AUTH_USER_MODEL)),
                ('subtipo', models.ForeignKey(blank=True, help_text='Opcional: restringe este checklist a um subtipo de item.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProjetoEstoque.subtipo')),
            ],
            options={
                'verbose_name': 'Modelo de Checklist',
                'verbose_name_plural': 'Modelos de Checklist',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CheckListPergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('texto_pergunta', models.CharField(max_length=255)),
                ('tipo_resposta', models.CharField(choices=[('texto', 'Texto'), ('numero', 'Número'), ('booleano', 'Sim/Não'), ('escolha', 'Escolha única')], default='texto', max_length=12)),
                ('obrigatorio', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='sim', max_length=3)),
                ('opcoes', models.CharField(blank=True, help_text='Para escolha única: separe opções por vírgula.', max_length=400, null=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('atualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizador', to=settings.AUTH_USER_MODEL)),
                ('checklist_modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='ProjetoEstoque.checklistmodelo')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pergunta de Checklist',
                'verbose_name_plural': 'Perguntas de Checklist',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Preventiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_ultima', models.DateField(blank=True, null=True)),
                ('data_proxima', models.DateField(blank=True, null=True)),
                ('dentro_do_prazo', models.BooleanField(default=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('atualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizador', to=settings.AUTH_USER_MODEL)),
                ('checklist_modelo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProjetoEstoque.checklistmodelo')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criador', to=settings.AUTH_USER_MODEL)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preventivas', to='ProjetoEstoque.item')),
            ],
            options={
                'verbose_name': 'Preventiva',
                'verbose_name_plural': 'Preventivas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PreventivaResposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resposta', models.TextField(blank=True, null=True)),
                ('atualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizador', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criador', to=settings.AUTH_USER_MODEL)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjetoEstoque.checklistpergunta')),
                ('preventiva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='ProjetoEstoque.preventiva')),
            ],
            options={
                'verbose_name': 'Resposta de Preventiva',
                'verbose_name_plural': 'Respostas de Preventiva',
            },
        ),
    ]
