# Generated by Django 5.2.1 on 2025-09-02 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0011_checklistmodelo_checklistpergunta_preventiva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localidade',
            name='codigo',
            field=models.CharField(blank=True, choices=[('karitel', 'Karitel'), ('Rio_do_Meio', 'Rio do Meio'), ('Mambai', 'mambai'), ('Sao Paulo', 'Sao_Paulo')], help_text='Sede: ', max_length=20, null=True),
        ),
    ]
