# Generated by Django 5.2.1 on 2025-06-07 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0011_remove_preventiva_realizada_dentro_prazo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='preventiva',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='preventiva',
            name='data_ultima',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='preventiva',
            name='dentro_do_prazo',
            field=models.CharField(choices=[('sim', 'Sim'), ('não', 'Não')], default='não', max_length=10),
        ),
    ]
