# Generated by Django 5.2.1 on 2025-09-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0012_alter_localidade_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaoitem',
            name='numero_pedido',
            field=models.CharField(blank=True, help_text='Obrigatório apenas para movimentações do tipo Entrada.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='localidade',
            name='codigo',
            field=models.CharField(blank=True, choices=[('Karitel', 'Karitel'), ('Rio_do_Meio', 'Rio do Meio'), ('Mambai', 'Mambai'), ('Sao_Paulo', 'Sao Paulo')], help_text='Sede: ', max_length=20, null=True),
        ),
    ]
