# Generated by Django 5.2.1 on 2025-06-08 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0013_equipamento_atualizado_por_equipamento_criado_por'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemPreventiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='preventivas/')),
                ('observacao', models.TextField(blank=True)),
                ('preventiva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='ProjetoEstoque.preventiva')),
            ],
        ),
    ]
