# Generated by Django 5.2.1 on 2025-09-06 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0013_movimentacaoitem_numero_pedido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventiva',
            name='foto_antes',
            field=models.ImageField(blank=True, null=True, upload_to='preventivas/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='preventiva',
            name='foto_depois',
            field=models.ImageField(blank=True, null=True, upload_to='preventivas/%Y/%m/'),
        ),
    ]
