# Generated by Django 5.2.1 on 2025-06-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0014_imagempreventiva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagempreventiva',
            name='observacao',
        ),
        migrations.AddField(
            model_name='imagempreventiva',
            name='descricao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
