# Generated by Django 5.2.1 on 2025-09-07 15:13

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0014_preventiva_foto_antes_preventiva_foto_depois'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='licenca',
            options={'ordering': ['-data_fim', 'produto__nome'], 'verbose_name': 'Licença', 'verbose_name_plural': 'Licenças'},
        ),
        migrations.RenameField(
            model_name='licenca',
            old_name='data_vencimento',
            new_name='data_fim',
        ),
        migrations.RenameField(
            model_name='licenca',
            old_name='observacoes',
            new_name='observacao',
        ),
        migrations.RenameField(
            model_name='licenca',
            old_name='quantidade',
            new_name='quantidade_total',
        ),
        migrations.RemoveField(
            model_name='licenca',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='licenca',
            name='tipo_licenca',
        ),
        migrations.RemoveField(
            model_name='licenca',
            name='valor',
        ),
        migrations.AddField(
            model_name='licenca',
            name='arquivo_contrato',
            field=models.FileField(blank=True, null=True, upload_to='contratos_licencas/'),
        ),
        migrations.AddField(
            model_name='licenca',
            name='auto_renovar',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='sim', max_length=3),
        ),
        migrations.AddField(
            model_name='licenca',
            name='centro_custo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProjetoEstoque.centrocusto'),
        ),
        migrations.AddField(
            model_name='licenca',
            name='data_inicio',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='licenca',
            name='moeda',
            field=models.CharField(default='BRL', max_length=6),
        ),
        migrations.AddField(
            model_name='licenca',
            name='numero_contrato',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='licenca',
            name='periodicidade',
            field=models.CharField(choices=[('mensal', 'Mensal'), ('semestral', 'Semestral'), ('anual', 'Anual'), ('trienal', 'Trienal'), ('contrato', 'Contrato (data fim definida)'), ('perpetua', 'Perpétua (sem vencimento)')], default='anual', max_length=12),
        ),
        migrations.AddField(
            model_name='licenca',
            name='pmb',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', max_length=3),
        ),
        migrations.AddField(
            model_name='licenca',
            name='status',
            field=models.CharField(choices=[('ativa', 'Ativa'), ('pendente', 'Pendente'), ('expirada', 'Expirada'), ('suspensa', 'Suspensa'), ('cancelada', 'Cancelada')], default='ativa', max_length=12),
        ),
        migrations.AddField(
            model_name='licenca',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='licenca',
            name='fornecedor',
            field=models.ForeignKey(blank=True, help_text='Se diferente do fornecedor do produto.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProjetoEstoque.fornecedor'),
        ),
        migrations.CreateModel(
            name='LicencaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=160)),
                ('exige_chave', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', max_length=3)),
                ('pmb', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', help_text='Se o produto é aplicado a usuários/processos PMB.', max_length=3)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('site_suporte', models.URLField(blank=True, null=True)),
                ('atualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizador', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criador', to=settings.AUTH_USER_MODEL)),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProjetoEstoque.fornecedor')),
            ],
            options={
                'verbose_name': 'Produto de Licença',
                'verbose_name_plural': 'Produtos de Licença',
                'ordering': ['nome'],
                'unique_together': {('nome', 'fornecedor')},
            },
        ),
        migrations.AddField(
            model_name='licenca',
            name='produto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='licencas', to='ProjetoEstoque.licencaproduto'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='LicencaAtribuicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_corporativo', models.EmailField(blank=True, max_length=254, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_atribuicao', models.DateField(default=django.utils.timezone.localdate)),
                ('data_desatribuicao', models.DateField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('atualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizador', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criador', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, help_text='Opcional: vincular a um equipamento específico.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProjetoEstoque.item')),
                ('licenca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atribuicoes', to='ProjetoEstoque.licenca')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licencas', to='ProjetoEstoque.usuario')),
            ],
            options={
                'verbose_name': 'Atribuição de Licença',
                'verbose_name_plural': 'Atribuições de Licenças',
                'ordering': ['-data_atribuicao', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('ativo', True)), fields=('licenca', 'usuario'), name='uniq_licenca_usuario_ativo'), models.UniqueConstraint(condition=models.Q(('ativo', True)), fields=('licenca', 'email_corporativo'), name='uniq_licenca_email_ativo')],
            },
        ),
    ]
