# Generated by Django 5.2.1 on 2025-06-08 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0015_remove_imagempreventiva_observacao_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImagemPreventiva',
        ),
    ]
