# Generated by Django 5.2.1 on 2025-09-07 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0015_alter_licenca_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licenca',
            name='produto',
        ),
        migrations.AlterModelOptions(
            name='licenca',
            options={'ordering': ['nome', '-data_fim'], 'verbose_name': 'Licença', 'verbose_name_plural': 'Licenças'},
        ),
        migrations.AddField(
            model_name='licenca',
            name='nome',
            field=models.CharField(default=1, max_length=160),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='licenca',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProjetoEstoque.fornecedor'),
        ),
        migrations.AlterField(
            model_name='licencaatribuicao',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProjetoEstoque.item'),
        ),
        migrations.DeleteModel(
            name='LicencaProduto',
        ),
    ]
