# Generated by Django 5.2.1 on 2025-06-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0016_delete_imagempreventiva'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventiva',
            name='status_led',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', max_length=3),
        ),
        migrations.AddField(
            model_name='preventiva',
            name='status_local_ap',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', max_length=3),
        ),
    ]
