# Generated by Django 5.2.1 on 2025-09-07 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0016_remove_licenca_produto_alter_licenca_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentacaoLicenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('atribuicao', 'Atribuição (−1 assento)'), ('revogacao', 'Revogação (+1 assento)'), ('transferencia', 'Transferência CC')], max_length=20)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('termo_pdf', models.FileField(blank=True, null=True, upload_to='licencas/termos/')),
            ],
            options={
                'verbose_name': 'Movimentação de Licença',
                'verbose_name_plural': 'Movimentações de Licença',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='licencaatribuicao',
            options={'ordering': ['-ativo', '-data_atribuicao', '-id']},
        ),
        migrations.RemoveConstraint(
            model_name='licencaatribuicao',
            name='uniq_licenca_usuario_ativo',
        ),
        migrations.RemoveConstraint(
            model_name='licencaatribuicao',
            name='uniq_licenca_email_ativo',
        ),
        migrations.RemoveField(
            model_name='licenca',
            name='arquivo_contrato',
        ),
        migrations.RemoveField(
            model_name='licenca',
            name='numero_contrato',
        ),
        migrations.RemoveField(
            model_name='licenca',
            name='quantidade_total',
        ),
        migrations.RemoveField(
            model_name='licencaatribuicao',
            name='email_corporativo',
        ),
        migrations.RemoveField(
            model_name='licencaatribuicao',
            name='item',
        ),
        migrations.AddField(
            model_name='licenca',
            name='quantidade',
            field=models.PositiveIntegerField(default=0, help_text='Assentos disponíveis'),
        ),
        migrations.AddField(
            model_name='licencaatribuicao',
            name='centro_custo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProjetoEstoque.centrocusto'),
        ),
        migrations.AddConstraint(
            model_name='licencaatribuicao',
            constraint=models.UniqueConstraint(condition=models.Q(('ativo', True), ('usuario__isnull', False)), fields=('licenca', 'usuario'), name='uniq_licenca_usuario_ativo_v2'),
        ),
        migrations.AddConstraint(
            model_name='licencaatribuicao',
            constraint=models.UniqueConstraint(condition=models.Q(('ativo', True), ('centro_custo__isnull', False)), fields=('licenca', 'centro_custo'), name='uniq_licenca_cc_ativo_v2'),
        ),
        migrations.AddField(
            model_name='movimentacaolicenca',
            name='atualizado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimentacaolicenca',
            name='centro_custo_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProjetoEstoque.centrocusto'),
        ),
        migrations.AddField(
            model_name='movimentacaolicenca',
            name='criado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimentacaolicenca',
            name='licenca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='ProjetoEstoque.licenca'),
        ),
        migrations.AddField(
            model_name='movimentacaolicenca',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProjetoEstoque.usuario'),
        ),
    ]
