# Generated by Django 5.2.1 on 2025-06-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0017_preventiva_status_led_preventiva_status_local_ap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preventiva',
            name='status_led',
        ),
        migrations.AddField(
            model_name='preventiva',
            name='copia_seguranca_ap',
            field=models.CharField(blank=True, choices=[('ok', 'Ok'), ('nao_ok', 'Não Ok')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='preventiva',
            name='limpeza_equipamento',
            field=models.CharField(blank=True, choices=[('ok', 'Ok'), ('nao_ok', 'Não Ok')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='preventiva',
            name='status_cabo_ethernet',
            field=models.CharField(blank=True, choices=[('ok', 'Ok'), ('nao_ok', 'Não Ok')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='preventiva',
            name='status_canais_ap',
            field=models.CharField(blank=True, choices=[('ok', 'Ok'), ('nao_ok', 'Não Ok')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='preventiva',
            name='status_cobertura_ap',
            field=models.CharField(blank=True, choices=[('ok', 'Ok'), ('nao_ok', 'Não Ok')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='preventiva',
            name='status_congestionamento',
            field=models.CharField(blank=True, choices=[('ok', 'Ok'), ('nao_ok', 'Não Ok')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='preventiva',
            name='status_failover',
            field=models.CharField(blank=True, choices=[('ok', 'Ok'), ('nao_ok', 'Não Ok')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='preventiva',
            name='status_firmware',
            field=models.CharField(blank=True, choices=[('ok', 'Ok'), ('nao_ok', 'Não Ok')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='preventiva',
            name='status_firmware_bkp',
            field=models.CharField(blank=True, choices=[('ok', 'Ok'), ('nao_ok', 'Não Ok')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='preventiva',
            name='status_leds',
            field=models.CharField(blank=True, choices=[('ok', 'Ok'), ('nao_ok', 'Não Ok')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='preventiva',
            name='status_temperatura',
            field=models.CharField(blank=True, choices=[('ok', 'Ok'), ('nao_ok', 'Não Ok')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='preventiva',
            name='status_teste_portas',
            field=models.CharField(blank=True, choices=[('ok', 'Ok'), ('nao_ok', 'Não Ok')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='preventiva',
            name='status_teste_rede',
            field=models.CharField(blank=True, choices=[('ok', 'Ok'), ('nao_ok', 'Não Ok')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='preventiva',
            name='status_velocidade_ap',
            field=models.CharField(blank=True, choices=[('ok', 'Ok'), ('nao_ok', 'Não Ok')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='preventiva',
            name='status_wps_ap',
            field=models.CharField(blank=True, choices=[('ok', 'Ok'), ('nao_ok', 'Não Ok')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='preventiva',
            name='status_local_ap',
            field=models.CharField(blank=True, choices=[('ok', 'Ok'), ('nao_ok', 'Não Ok')], max_length=10, null=True),
        ),
    ]
