# Generated by Django 5.2.1 on 2025-09-08 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0017_movimentacaolicenca_alter_licencaatribuicao_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='licenca',
            options={'ordering': ['nome'], 'verbose_name': 'Licença', 'verbose_name_plural': 'Licenças'},
        ),
        migrations.AlterModelOptions(
            name='movimentacaolicenca',
            options={'ordering': ['-created_at'], 'verbose_name': 'Movimentação de Licença', 'verbose_name_plural': 'Movimentações de Licenças'},
        ),
        migrations.RemoveField(
            model_name='licenca',
            name='auto_renovar',
        ),
        migrations.RemoveField(
            model_name='licenca',
            name='moeda',
        ),
        migrations.RemoveField(
            model_name='licenca',
            name='status',
        ),
        migrations.RemoveField(
            model_name='licenca',
            name='valor_total',
        ),
        migrations.RemoveField(
            model_name='movimentacaolicenca',
            name='quantidade',
        ),
        migrations.RemoveField(
            model_name='movimentacaolicenca',
            name='termo_pdf',
        ),
        migrations.AlterField(
            model_name='licenca',
            name='data_inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='licenca',
            name='periodicidade',
            field=models.CharField(choices=[('mensal', 'Mensal'), ('semestral', 'Semestral'), ('anual', 'Anual'), ('trienal', 'Trienal'), ('contrato', 'Contrato/Outro')], default='mensal', max_length=16),
        ),
        migrations.AlterField(
            model_name='licenca',
            name='quantidade',
            field=models.PositiveIntegerField(default=0, help_text='Assentos disponíveis para atribuição.'),
        ),
        migrations.AlterField(
            model_name='movimentacaolicenca',
            name='centro_custo_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mov_licencas_destino', to='ProjetoEstoque.centrocusto'),
        ),
        migrations.AlterField(
            model_name='movimentacaolicenca',
            name='tipo',
            field=models.CharField(choices=[('atribuicao', 'Atribuição'), ('remocao', 'Remoção')], max_length=16),
        ),
        migrations.AlterField(
            model_name='movimentacaolicenca',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mov_licencas', to='ProjetoEstoque.usuario'),
        ),
        migrations.DeleteModel(
            name='LicencaAtribuicao',
        ),
    ]
