# Generated by Django 5.2.1 on 2025-06-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0018_remove_preventiva_status_led_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventiva',
            name='imagem_antes',
            field=models.ImageField(blank=True, null=True, upload_to='preventivas/antes/'),
        ),
        migrations.AddField(
            model_name='preventiva',
            name='imagem_depois',
            field=models.ImageField(blank=True, null=True, upload_to='preventivas/depois/'),
        ),
    ]
