# Generated by Django 5.2.1 on 2025-09-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0018_alter_licenca_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenca',
            name='custo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custo do ciclo (ex.: mensal, anual, etc.)', max_digits=12, null=True),
        ),
    ]
