# Generated by Django 5.2.1 on 2025-06-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0019_preventiva_imagem_antes_preventiva_imagem_depois'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='numero_serie',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
