# Generated by Django 5.2.1 on 2025-09-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0019_licenca_custo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenca',
            name='custo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custo do ciclo conforme periodicidade.', max_digits=12, null=True),
        ),
    ]
