# Generated by Django 5.2.1 on 2025-06-25 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0022_alter_equipamento_local'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preventiva',
            name='copia_seguranca_ap',
        ),
        migrations.RemoveField(
            model_name='preventiva',
            name='status_canais_ap',
        ),
        migrations.RemoveField(
            model_name='preventiva',
            name='status_congestionamento',
        ),
        migrations.RemoveField(
            model_name='preventiva',
            name='status_failover',
        ),
        migrations.RemoveField(
            model_name='preventiva',
            name='status_firmware',
        ),
        migrations.RemoveField(
            model_name='preventiva',
            name='status_firmware_bkp',
        ),
        migrations.RemoveField(
            model_name='preventiva',
            name='status_wps_ap',
        ),
    ]
