# Generated by Django 5.2.1 on 2025-09-12 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0022_movlicenca_add_lote_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='licencalote',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Lote de Licença', 'verbose_name_plural': 'Lotes de Licenças'},
        ),
        migrations.AddField(
            model_name='movimentacaolicenca',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes', to='ProjetoEstoque.licencalote'),
        ),
        migrations.AlterField(
            model_name='licencalote',
            name='atualizado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='licencalote',
            name='criado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='licencalote',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
