# Generated by Django 5.2.1 on 2025-06-26 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0023_remove_preventiva_copia_seguranca_ap_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamento',
            name='estoque_minimo',
        ),
    ]
