# Generated by Django 5.2.1 on 2025-07-04 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0025_historicomanutencao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicomanutencao',
            name='equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_manutencoes', to='ProjetoEstoque.equipamento'),
        ),
        migrations.AlterField(
            model_name='historicomanutencao',
            name='tipo',
            field=models.CharField(max_length=50),
        ),
    ]
