# Generated by Django 5.2.1 on 2025-09-17 13:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0025_preventiva_execucao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='preventivaexecucao',
            name='atualizado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='preventivaexecucao',
            name='criado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='preventivaexecucao',
            name='data_execucao',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='preventivaexecucao',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='preventivaexecucao',
            name='preventiva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execucoes', to='ProjetoEstoque.preventiva'),
        ),
        migrations.AlterField(
            model_name='preventivaresposta',
            name='execucao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='ProjetoEstoque.preventivaexecucao'),
        ),
    ]
