# Generated by Django 5.2.1 on 2025-09-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0026_alter_preventivaexecucao_atualizado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preventivaexecucao',
            name='data_execucao',
            field=models.DateField(),
        ),
    ]
