# Generated by Django 5.2.1 on 2025-07-04 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0026_alter_historicomanutencao_equipamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicomanutencao',
            name='equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='ProjetoEstoque.equipamento'),
        ),
    ]
