# Generated by Django 5.2.1 on 2025-07-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0027_alter_historicomanutencao_equipamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='causa_problema',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='custo_reparo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
