# Generated by Django 5.2.1 on 2025-09-18 14:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0027_alter_preventivaexecucao_data_execucao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preventivaexecucao',
            name='data_execucao',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='preventivaresposta',
            name='execucao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='ProjetoEstoque.preventivaexecucao'),
            preserve_default=False,
        ),
    ]
