# Generated by Django 5.2.1 on 2025-07-04 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0028_equipamento_causa_problema_equipamento_custo_reparo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamento',
            name='causa_problema',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='custo_reparo',
        ),
    ]
