# Generated by Django 5.2.7 on 2025-12-04 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0028_alter_preventivaexecucao_data_execucao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaoitem',
            name='tipo_movimentacao',
            field=models.CharField(choices=[('transferencia', 'Transferência'), ('transferencia_equipamento', 'Transferência Equipamento'), ('baixa', 'Baixa'), ('entrada', 'Entrada'), ('envio_manutencao', 'Envio para Manutenção'), ('retorno_manutencao', 'Retorno de Manutenção'), ('outros', 'Outros')], max_length=30),
        ),
    ]
