# Generated by Django 5.2.7 on 2025-12-04 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0029_alter_movimentacaoitem_tipo_movimentacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaoitem',
            name='status_transferencia',
            field=models.CharField(blank=True, choices=[('ativo', 'Ativo'), ('backup', 'Backup'), ('manutencao', 'Manutenção'), ('defeito', 'Defeito'), ('pausado', 'Pausado')], help_text='Status desejado do equipamento na transferência de equipamento.', max_length=15, null=True),
        ),
    ]
