# Generated by Django 5.2.1 on 2025-07-04 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0029_remove_equipamento_causa_problema_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicomanutencao',
            old_name='causa',
            new_name='causa_problema',
        ),
        migrations.RenameField(
            model_name='historicomanutencao',
            old_name='custo',
            new_name='custo_reparo',
        ),
    ]
