# Generated by Django 5.2.1 on 2025-07-04 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0030_rename_causa_historicomanutencao_causa_problema_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricoManutencao',
        ),
    ]
