# Generated by Django 5.2.7 on 2025-12-19 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0030_movimentacaoitem_status_transferencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaoitem',
            name='centro_custo_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movs_destino_cc', to='ProjetoEstoque.centrocusto'),
        ),
        migrations.AlterField(
            model_name='movimentacaoitem',
            name='centro_custo_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movs_origem_cc', to='ProjetoEstoque.centrocusto'),
        ),
    ]
