# Generated by Django 5.2.7 on 2026-01-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0031_alter_movimentacaoitem_centro_custo_destino_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='licencalote',
            options={'ordering': ['-id'], 'verbose_name': 'Lote de Licença', 'verbose_name_plural': 'Lotes de Licenças'},
        ),
        migrations.AddField(
            model_name='licencalote',
            name='numero_pedido',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='licencalote',
            name='periodicidade',
            field=models.CharField(choices=[('mensal', 'Mensal'), ('semestral', 'Semestral'), ('anual', 'Anual'), ('trienal', 'Trienal')], default='anual', max_length=20),
        ),
    ]
