# Generated by Django 5.2.7 on 2026-01-11 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0032_alter_licencalote_options_licencalote_numero_pedido_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='licencalote',
            options={'ordering': ['-data_compra', '-id'], 'verbose_name': 'Lote de Licença', 'verbose_name_plural': 'Lotes de Licenças'},
        ),
        migrations.AddField(
            model_name='movimentacaolicenca',
            name='valor_unitario_lote',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custo unitário deste item no lote de origem', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='licencalote',
            name='custo_ciclo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Custo do Lote'),
        ),
        migrations.AlterField(
            model_name='licencalote',
            name='numero_pedido',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº Pedido/NF'),
        ),
        migrations.AlterField(
            model_name='licencalote',
            name='periodicidade',
            field=models.CharField(choices=[('mensal', 'Mensal'), ('semestral', 'Semestral'), ('anual', 'Anual'), ('trienal', 'Trienal'), ('vitalicia', 'Vitalícia/Perpétua')], default='anual', max_length=20),
        ),
        migrations.AlterField(
            model_name='licencalote',
            name='quantidade_disponivel',
            field=models.PositiveIntegerField(verbose_name='Saldo Disponível'),
        ),
        migrations.AlterField(
            model_name='licencalote',
            name='quantidade_total',
            field=models.PositiveIntegerField(verbose_name='Qtd. Comprada'),
        ),
    ]
