# Generated by Django 5.2.1 on 2025-07-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0032_historicomanutencao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicomanutencao',
            old_name='data',
            new_name='data_criacao',
        ),
        migrations.AlterField(
            model_name='historicomanutencao',
            name='tipo',
            field=models.CharField(choices=[('manutencao', 'Manutenção'), ('retorno', 'Retorno de Manutenção'), ('queima', 'Equipamento Queimado')], max_length=20),
        ),
    ]
