# Generated by Django 5.2.7 on 2026-01-11 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0033_alter_licencalote_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentacaolicenca',
            name='valor_unitario_lote',
        ),
        migrations.AddField(
            model_name='movimentacaolicenca',
            name='valor_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='movimentacaolicenca',
            name='centro_custo_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProjetoEstoque.centrocusto'),
        ),
        migrations.AlterField(
            model_name='movimentacaolicenca',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProjetoEstoque.licencalote'),
        ),
        migrations.AlterField(
            model_name='movimentacaolicenca',
            name='tipo',
            field=models.CharField(choices=[('atribuicao', 'Atribuição'), ('remocao', 'Remoção')], max_length=20),
        ),
        migrations.AlterField(
            model_name='movimentacaolicenca',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProjetoEstoque.usuario'),
        ),
    ]
