# Generated by Django 5.2.7 on 2026-01-11 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0034_remove_movimentacaolicenca_valor_unitario_lote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaolicenca',
            name='tipo',
            field=models.CharField(choices=[('atribuicao', 'Atribuição (Saída)'), ('devolucao', 'Devolução (Entrada)')], max_length=20),
        ),
    ]
