# Generated by Django 5.2.1 on 2025-07-04 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0034_alter_historicomanutencao_autor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicomanutencao',
            name='tipo',
            field=models.CharField(choices=[('queima', 'Equipamento Queimado'), ('retorno', 'Retorno de Manutenção')], max_length=20),
        ),
    ]
