# Generated by Django 5.2.7 on 2026-01-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0035_alter_movimentacaolicenca_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='licencalote',
            options={'ordering': ['-data_compra', '-id'], 'verbose_name': 'Lote de Licença'},
        ),
        migrations.AlterModelOptions(
            name='movimentacaolicenca',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='licencalote',
            name='custo_ciclo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='licencalote',
            name='numero_pedido',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='licencalote',
            name='periodicidade',
            field=models.CharField(choices=[('mensal', 'Mensal'), ('anual', 'Anual'), ('trienal', 'Trienal')], default='anual', max_length=20),
        ),
        migrations.AlterField(
            model_name='licencalote',
            name='quantidade_disponivel',
            field=models.PositiveIntegerField(default=0, verbose_name='Saldo Disponível'),
        ),
    ]
