# Generated by Django 5.2.7 on 2026-01-11 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0036_alter_licencalote_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licencalote',
            name='periodicidade',
            field=models.CharField(choices=[('mensal', 'Mensal'), ('anual', 'Anual'), ('trienal', 'Trienal'), ('perpetua', 'Perpétua')], default='anual', max_length=20),
        ),
    ]
