# Generated by Django 5.2.7 on 2026-01-11 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0037_alter_licencalote_periodicidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenca',
            name='custo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Custo do Contrato (R$)'),
        ),
        migrations.AlterField(
            model_name='licenca',
            name='data_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Fim da Vigência'),
        ),
        migrations.AlterField(
            model_name='licenca',
            name='data_inicio',
            field=models.DateField(verbose_name='Início da Vigência'),
        ),
        migrations.AlterField(
            model_name='licenca',
            name='nome',
            field=models.CharField(max_length=160, verbose_name='Nome do Software/Licença'),
        ),
        migrations.AlterField(
            model_name='licenca',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='licenca',
            name='periodicidade',
            field=models.CharField(choices=[('mensal', 'Mensal'), ('semestral', 'Semestral'), ('anual', 'Anual'), ('trienal', 'Trienal'), ('contrato', 'Contrato/Outro')], default='anual', max_length=16),
        ),
        migrations.AlterField(
            model_name='licenca',
            name='pmb',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', max_length=3, verbose_name='PMB?'),
        ),
        migrations.AlterField(
            model_name='licenca',
            name='quantidade',
            field=models.PositiveIntegerField(default=0, help_text='Número de licenças disponíveis para atribuição.', verbose_name='Quantidade / Saldo Disponível'),
        ),
    ]
