# Generated by Django 5.2.7 on 2026-01-11 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0038_alter_licenca_custo_alter_licenca_data_fim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenca',
            name='quantidade_total',
            field=models.PositiveIntegerField(default=1, help_text='Total de assentos adquiridos no contrato.', verbose_name='Qtd. Total Contratada'),
        ),
        migrations.AlterField(
            model_name='licenca',
            name='custo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Custo R$'),
        ),
        migrations.AlterField(
            model_name='licenca',
            name='data_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Fim Vigência'),
        ),
        migrations.AlterField(
            model_name='licenca',
            name='data_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Início Vigência'),
        ),
        migrations.AlterField(
            model_name='licenca',
            name='nome',
            field=models.CharField(max_length=160, verbose_name='Nome da Licença'),
        ),
        migrations.AlterField(
            model_name='licenca',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='licenca',
            name='quantidade',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Saldo Disponível'),
        ),
    ]
