# Generated by Django 5.2.7 on 2026-01-11 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0039_licenca_quantidade_total_alter_licenca_custo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licenca',
            name='centro_custo',
        ),
        migrations.RemoveField(
            model_name='licenca',
            name='custo',
        ),
        migrations.RemoveField(
            model_name='licenca',
            name='data_fim',
        ),
        migrations.RemoveField(
            model_name='licenca',
            name='data_inicio',
        ),
        migrations.RemoveField(
            model_name='licenca',
            name='periodicidade',
        ),
        migrations.RemoveField(
            model_name='licenca',
            name='quantidade',
        ),
        migrations.RemoveField(
            model_name='licenca',
            name='quantidade_total',
        ),
        migrations.AlterField(
            model_name='licenca',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProjetoEstoque.fornecedor', verbose_name='Fornecedor'),
        ),
        migrations.AlterField(
            model_name='licenca',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
    ]
