# Generated by Django 5.2.7 on 2026-01-12 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0040_remove_licenca_centro_custo_remove_licenca_custo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimentacaolicenca',
            options={'ordering': ['-created_at'], 'verbose_name': 'Movimentação de Licença'},
        ),
        migrations.AddField(
            model_name='licenca',
            name='centro_custo',
            field=models.ForeignKey(blank=True, help_text='Centro de Custo proprietário (ex: TI) para onde o ativo volta na devolução.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProjetoEstoque.centrocusto'),
        ),
        migrations.AlterField(
            model_name='licenca',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProjetoEstoque.fornecedor'),
        ),
        migrations.AlterField(
            model_name='licenca',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='licencalote',
            name='periodicidade',
            field=models.CharField(default='anual', max_length=20),
        ),
    ]
