# Generated by Django 5.2.7 on 2026-01-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0041_alter_movimentacaolicenca_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licencalote',
            name='periodicidade',
            field=models.CharField(choices=[('mensal', 'Mensal'), ('semestral', 'Semestral'), ('anual', 'Anual'), ('trienal', 'Trienal'), ('contrato', 'Contrato/Outro')], default='anual', max_length=20),
        ),
    ]
