# Generated by Django 5.2.7 on 2026-01-12 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0042_alter_licencalote_periodicidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaoitem',
            name='numero_pedido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movimentacaoitem',
            name='status_transferencia',
            field=models.CharField(blank=True, choices=[('ativo', 'Ativo'), ('backup', 'Backup'), ('manutencao', 'Manutenção'), ('defeito', 'Defeito'), ('pausado', 'Pausado')], help_text='Status desejado do equipamento na transferência.', max_length=15, null=True),
        ),
    ]
