# Generated by Django 5.2.7 on 2026-01-12 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0043_alter_movimentacaoitem_numero_pedido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaoitem',
            name='chamado',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nº Chamado'),
        ),
        migrations.AlterField(
            model_name='movimentacaoitem',
            name='custo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Custo Total'),
        ),
        migrations.AlterField(
            model_name='movimentacaoitem',
            name='numero_pedido',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nº Pedido/NF'),
        ),
        migrations.AlterField(
            model_name='movimentacaoitem',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='movimentacaoitem',
            name='status_transferencia',
            field=models.CharField(blank=True, choices=[('ativo', 'Ativo'), ('backup', 'Backup'), ('manutencao', 'Manutenção'), ('defeito', 'Defeito'), ('pausado', 'Pausado')], help_text='Define o status do item após a transferência de equipamento.', max_length=15, null=True, verbose_name='Novo Status'),
        ),
        migrations.AlterField(
            model_name='movimentacaoitem',
            name='termo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='termos/', verbose_name='Termo de Responsabilidade'),
        ),
        migrations.AlterField(
            model_name='movimentacaoitem',
            name='tipo_transferencia',
            field=models.CharField(blank=True, choices=[('entrega', 'Entrega'), ('devolucao', 'Devolução')], help_text='Obrigatório se Tipo for Transferência.', max_length=10, null=True),
        ),
    ]
