# Generated by Django 5.2.7 on 2026-01-13 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0044_alter_movimentacaoitem_chamado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaoitem',
            name='custo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Custo da Operação'),
        ),
        migrations.AlterField(
            model_name='movimentacaoitem',
            name='status_transferencia',
            field=models.CharField(blank=True, choices=[('ativo', 'Ativo'), ('backup', 'Backup'), ('manutencao', 'Manutenção'), ('defeito', 'Defeito'), ('pausado', 'Pausado')], help_text='Status desejado após transferência de equipamento.', max_length=15, null=True, verbose_name='Novo Status'),
        ),
        migrations.AlterField(
            model_name='movimentacaoitem',
            name='tipo_transferencia',
            field=models.CharField(blank=True, choices=[('entrega', 'Entrega'), ('devolucao', 'Devolução')], help_text='Define se é entrega ao usuário ou devolução.', max_length=10, null=True),
        ),
    ]
