# Generated by Django 5.2.7 on 2026-01-13 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0045_alter_movimentacaoitem_custo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaoitem',
            name='status_transferencia',
            field=models.CharField(blank=True, choices=[('ativo', 'Ativo'), ('backup', 'Backup'), ('manutencao', 'Manutenção'), ('defeito', 'Defeito'), ('pausado', 'Pausado')], max_length=15, null=True, verbose_name='Novo Status'),
        ),
        migrations.AlterField(
            model_name='movimentacaoitem',
            name='tipo_transferencia',
            field=models.CharField(blank=True, choices=[('entrega', 'Entrega'), ('devolucao', 'Devolução')], max_length=10, null=True),
        ),
    ]
