# Generated by Django 5.2.7 on 2026-01-17 13:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0046_alter_movimentacaoitem_status_transferencia_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='data_compra',
        ),
        migrations.AddField(
            model_name='item',
            name='data_entrada',
            field=models.DateField(blank=True, help_text='Data base para cálculos de depreciação ou vigência de contrato.', null=True, verbose_name='Data de Entrada / Início'),
        ),
        migrations.AlterField(
            model_name='item',
            name='data_limite_preventiva',
            field=models.IntegerField(blank=True, help_text='Periodicidade em dias (Inteiro)', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='locado',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', max_length=3, verbose_name='É Locado?'),
        ),
        migrations.AlterField(
            model_name='item',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do Item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='numero_pedido',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Doc. Origem (NF/Contrato)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Série'),
        ),
        migrations.AlterField(
            model_name='item',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Unitário (Ref.)'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['numero_serie'], name='ProjetoEsto_numero__39cdcd_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['status'], name='ProjetoEsto_status_7ed6bd_idx'),
        ),
    ]
