# Generated by Django 5.2.7 on 2026-01-17 14:47

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0047_remove_item_data_compra_item_data_entrada_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Itens'},
        ),
        migrations.RemoveIndex(
            model_name='item',
            name='ProjetoEsto_numero__39cdcd_idx',
        ),
        migrations.RemoveIndex(
            model_name='item',
            name='ProjetoEsto_status_7ed6bd_idx',
        ),
        migrations.RemoveField(
            model_name='item',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='locacao',
            name='contrato',
        ),
        migrations.RemoveField(
            model_name='locacao',
            name='fornecedor',
        ),
        migrations.AddField(
            model_name='locacao',
            name='arquivo_contrato',
            field=models.FileField(blank=True, null=True, upload_to='contratos/%Y/', verbose_name='Anexo (PDF)'),
        ),
        migrations.AddField(
            model_name='locacao',
            name='numero_contrato',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nº do Contrato'),
        ),
        migrations.AlterField(
            model_name='item',
            name='data_entrada',
            field=models.DateField(blank=True, help_text='Data física de recebimento ou início da vigência do contrato.', null=True, verbose_name='Data de Entrada / Início'),
        ),
        migrations.AlterField(
            model_name='item',
            name='data_limite_preventiva',
            field=models.IntegerField(blank=True, help_text='Periodicidade em dias', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProjetoEstoque.fornecedor', verbose_name='Fornecedor / Locador'),
        ),
        migrations.AlterField(
            model_name='item',
            name='numero_pedido',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Doc. Origem (NF/Pedido)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantidade',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Obs. Contratuais'),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='tempo_locado',
            field=models.IntegerField(blank=True, null=True, verbose_name='Vigência (Meses)'),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='valor_mensal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor Mensal (R$)'),
        ),
    ]
