# Generated by Django 5.2.7 on 2026-01-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0048_alter_item_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['nome'], 'verbose_name': 'Item', 'verbose_name_plural': 'Itens'},
        ),
        migrations.AlterField(
            model_name='item',
            name='numero_pedido',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Doc. Origem (NF/Contrato)'),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='tempo_locado',
            field=models.IntegerField(blank=True, help_text='Duração do contrato em meses', null=True, verbose_name='Vigência (Meses)'),
        ),
    ]
