# Generated by Django 5.2.7 on 2026-01-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0049_alter_item_options_alter_item_numero_pedido_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Itens'},
        ),
        migrations.AlterField(
            model_name='item',
            name='data_entrada',
            field=models.DateField(blank=True, help_text='Data da Nota Fiscal ou Início do Contrato de Locação', null=True, verbose_name='Data de Entrada'),
        ),
        migrations.AlterField(
            model_name='item',
            name='data_limite_preventiva',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='numero_pedido',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Doc. Origem (NF/Pedido)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Unitário'),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='tempo_locado',
            field=models.IntegerField(blank=True, null=True, verbose_name='Vigência (Meses)'),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='valor_mensal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Mensal (R$)'),
        ),
    ]
