# Generated by Django 5.2.7 on 2026-01-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0050_alter_item_options_alter_item_data_entrada_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={},
        ),
        migrations.AlterField(
            model_name='item',
            name='data_entrada',
            field=models.DateField(blank=True, help_text='Data da Nota Fiscal (Compra) ou Início do Contrato (Locação)', null=True, verbose_name='Data de Entrada'),
        ),
        migrations.AlterField(
            model_name='item',
            name='numero_pedido',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Doc. Origem'),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='arquivo_contrato',
            field=models.FileField(blank=True, null=True, upload_to='contratos/%Y/', verbose_name='Anexo'),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='numero_contrato',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nº Contrato'),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Obs. Contrato'),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='valor_mensal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Mensal'),
        ),
    ]
