# Generated by Django 5.2.7 on 2026-01-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0051_alter_item_options_alter_item_data_entrada_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Itens'},
        ),
        migrations.AlterField(
            model_name='item',
            name='data_entrada',
            field=models.DateField(blank=True, help_text='Data da nota fiscal ou início do contrato.', null=True, verbose_name='Data de Entrada'),
        ),
    ]
