# Generated by Django 5.2.7 on 2026-01-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0052_alter_item_options_alter_item_data_entrada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='data_entrada',
        ),
        migrations.AddField(
            model_name='item',
            name='data_compra',
            field=models.DateField(blank=True, help_text='Data de emissão da Nota Fiscal (apenas para itens próprios).', null=True, verbose_name='Data da Compra'),
        ),
        migrations.AddField(
            model_name='locacao',
            name='data_entrada',
            field=models.DateField(blank=True, help_text='Data de início do contrato ou recebimento físico.', null=True, verbose_name='Data de Entrada'),
        ),
    ]
