# Generated by Django 5.2.7 on 2026-01-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0053_remove_item_data_entrada_item_data_compra_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='data_compra',
        ),
        migrations.RemoveField(
            model_name='locacao',
            name='arquivo_contrato',
        ),
        migrations.RemoveField(
            model_name='locacao',
            name='data_entrada',
        ),
        migrations.AddField(
            model_name='item',
            name='data_entrada',
            field=models.DateField(blank=True, help_text='Data da Nota Fiscal ou Início do Contrato', null=True, verbose_name='Data de Entrada'),
        ),
    ]
