# Generated by Django 5.2.7 on 2026-01-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0054_remove_item_data_compra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='data_entrada',
            field=models.DateField(blank=True, help_text='Data da Nota Fiscal ou Início do Contrato.', null=True, verbose_name='Data de Entrada'),
        ),
    ]
