# Generated by Django 5.2.7 on 2026-01-17 16:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0055_alter_item_data_entrada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Item / Equipamento', 'verbose_name_plural': 'Itens / Equipamentos'},
        ),
        migrations.RemoveField(
            model_name='item',
            name='data_entrada',
        ),
        migrations.RemoveField(
            model_name='locacao',
            name='numero_contrato',
        ),
        migrations.AddField(
            model_name='item',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProjetoEstoque.categoria'),
        ),
        migrations.AddField(
            model_name='item',
            name='data_compra',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locacao',
            name='contrato',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='locacao',
            name='data_entrada',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Entrada (Locação)'),
        ),
        migrations.AddField(
            model_name='locacao',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProjetoEstoque.fornecedor'),
        ),
        migrations.AlterField(
            model_name='item',
            name='data_limite_preventiva',
            field=models.IntegerField(blank=True, help_text='Dias para nova preventiva', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProjetoEstoque.fornecedor'),
        ),
        migrations.AlterField(
            model_name='item',
            name='locado',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', max_length=3),
        ),
        migrations.AlterField(
            model_name='item',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='numero_pedido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='tempo_locado',
            field=models.IntegerField(blank=True, help_text='Informe a quantidade de meses', null=True),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='valor_mensal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor do pagamento mensal (R$)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
