# Generated by Django 5.2.7 on 2026-01-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0056_alter_item_options_remove_item_data_entrada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locacao',
            name='data_entrada',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Entrada (Início)'),
        ),
    ]
