# Generated by Django 5.2.7 on 2026-01-17 16:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0057_alter_locacao_data_entrada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Itens'},
        ),
        migrations.RemoveField(
            model_name='item',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='locacao',
            name='fornecedor',
        ),
        migrations.AlterField(
            model_name='item',
            name='data_compra',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Compra'),
        ),
        migrations.AlterField(
            model_name='item',
            name='data_limite_preventiva',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProjetoEstoque.fornecedor', verbose_name='Fornecedor / Locador'),
        ),
        migrations.AlterField(
            model_name='item',
            name='locado',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', max_length=3, verbose_name='É Locado?'),
        ),
        migrations.AlterField(
            model_name='item',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do Item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='numero_pedido',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Doc. Origem'),
        ),
        migrations.AlterField(
            model_name='item',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Série'),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantidade',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='item',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Unitário'),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='contrato',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nº Contrato'),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='data_entrada',
            field=models.DateField(blank=True, null=True, verbose_name='Início do Contrato'),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Obs. Contrato'),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='tempo_locado',
            field=models.IntegerField(blank=True, null=True, verbose_name='Vigência (Meses)'),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='valor_mensal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Mensal'),
        ),
    ]
