# Generated by Django 5.2.7 on 2026-04-29 02:04

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0059_alter_item_options_item_categoria_locacao_fornecedor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tem_lote',
            field=models.BooleanField(default=False, verbose_name='Controlar por lote?'),
        ),
        migrations.CreateModel(
            name='LoteEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_entrada', models.DateField(verbose_name='Data de Entrada')),
                ('numero_nf', models.CharField(max_length=60, verbose_name='Número da NF')),
                ('serie_nf', models.CharField(max_length=30, verbose_name='Série da NF')),
                ('quantidade', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade do Lote')),
                ('custo_unitario', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Custo Unitário')),
                ('custo_total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Custo Total')),
                ('observacao_tecnica', models.TextField(blank=True, null=True, verbose_name='Observação Técnica')),
                ('atualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizador', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criador', to=settings.AUTH_USER_MODEL)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_estoque', to='ProjetoEstoque.fornecedor', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'Lote de Estoque',
                'verbose_name_plural': 'Lotes de Estoque',
                'ordering': ['-data_entrada', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantidade_entrada', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade de Entrada')),
                ('quantidade_disponivel', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade Disponível')),
                ('custo_unitario', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Custo Unitário')),
                ('custo_total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Custo Total')),
                ('atualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizador', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criador', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vinculos_lote', to='ProjetoEstoque.item', verbose_name='Item / Equipamento')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_vinculados', to='ProjetoEstoque.loteestoque', verbose_name='Lote')),
            ],
            options={
                'verbose_name': 'Vínculo Item x Lote',
                'verbose_name_plural': 'Vínculos Item x Lote',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='movimentacaoitem',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='ProjetoEstoque.loteestoque', verbose_name='Lote vinculado'),
        ),
        migrations.AddIndex(
            model_name='loteestoque',
            index=models.Index(fields=['numero_nf', 'serie_nf'], name='ProjetoEsto_numero__4f07c8_idx'),
        ),
        migrations.AddIndex(
            model_name='loteestoque',
            index=models.Index(fields=['data_entrada'], name='ProjetoEsto_data_en_79fe6e_idx'),
        ),
    ]
