# Generated by Django 5.2.7 on 2026-04-29 19:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0060_item_tem_lote_loteestoque_itemlote_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='loteestoque',
            name='ProjetoEsto_numero__4f07c8_idx',
        ),
        migrations.RemoveField(
            model_name='itemlote',
            name='custo_total',
        ),
        migrations.RemoveField(
            model_name='loteestoque',
            name='custo_total',
        ),
        migrations.RemoveField(
            model_name='loteestoque',
            name='serie_nf',
        ),
        migrations.AddIndex(
            model_name='itemlote',
            index=models.Index(fields=['item'], name='ProjetoEsto_item_id_f61149_idx'),
        ),
        migrations.AddIndex(
            model_name='itemlote',
            index=models.Index(fields=['lote'], name='ProjetoEsto_lote_id_efcaae_idx'),
        ),
        migrations.AddIndex(
            model_name='loteestoque',
            index=models.Index(fields=['numero_nf'], name='ProjetoEsto_numero__5f4653_idx'),
        ),
        migrations.AddIndex(
            model_name='loteestoque',
            index=models.Index(fields=['fornecedor'], name='ProjetoEsto_fornece_2caf48_idx'),
        ),
    ]
