# Generated by Django 5.2.7 on 2026-04-30 17:01

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0061_remove_loteestoque_projetoesto_numero__4f07c8_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['nome']},
        ),
        migrations.AddField(
            model_name='usuario',
            name='matricula',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='movimentacaoitem',
            name='centro_custo_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movs_destino_cc', to='ProjetoEstoque.centrocusto', verbose_name='Centro de Custo Destino'),
        ),
        migrations.AlterField(
            model_name='movimentacaoitem',
            name='centro_custo_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movs_origem_cc', to='ProjetoEstoque.centrocusto', verbose_name='Centro de Custo Origem'),
        ),
        migrations.AlterField(
            model_name='movimentacaoitem',
            name='custo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Custo da Operação'),
        ),
        migrations.AlterField(
            model_name='movimentacaoitem',
            name='fornecedor_manutencao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manutencoes', to='ProjetoEstoque.fornecedor', verbose_name='Fornecedor Manutenção'),
        ),
        migrations.AlterField(
            model_name='movimentacaoitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='ProjetoEstoque.item', verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='movimentacaoitem',
            name='localidade_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movs_destino', to='ProjetoEstoque.localidade', verbose_name='Localidade de Destino'),
        ),
        migrations.AlterField(
            model_name='movimentacaoitem',
            name='localidade_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movs_origem', to='ProjetoEstoque.localidade', verbose_name='Localidade de Origem'),
        ),
        migrations.AlterField(
            model_name='movimentacaoitem',
            name='quantidade',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='movimentacaoitem',
            name='status_retorno',
            field=models.CharField(blank=True, choices=[('ativo', 'Ativo'), ('backup', 'Backup'), ('manutencao', 'Manutenção'), ('defeito', 'Defeito'), ('pausado', 'Pausado')], max_length=15, null=True, verbose_name='Status Retorno'),
        ),
        migrations.AlterField(
            model_name='movimentacaoitem',
            name='tipo_movimentacao',
            field=models.CharField(choices=[('transferencia', 'Transferência'), ('transferencia_equipamento', 'Transferência Equipamento'), ('baixa', 'Baixa'), ('entrada', 'Entrada'), ('envio_manutencao', 'Envio para Manutenção'), ('retorno_manutencao', 'Retorno de Manutenção'), ('outros', 'Outros')], max_length=30, verbose_name='Tipo de Movimentação'),
        ),
        migrations.AlterField(
            model_name='movimentacaoitem',
            name='tipo_transferencia',
            field=models.CharField(blank=True, choices=[('entrega', 'Entrega'), ('devolucao', 'Devolução')], max_length=10, null=True, verbose_name='Tipo de Transferência'),
        ),
        migrations.AlterField(
            model_name='movimentacaoitem',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes', to='ProjetoEstoque.usuario', verbose_name='Usuário / Solicitante'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='centro_custo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProjetoEstoque.centrocusto'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='funcao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProjetoEstoque.funcao'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='localidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProjetoEstoque.localidade'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['matricula'], name='ProjetoEsto_matricu_b13912_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['nome'], name='ProjetoEsto_nome_5be7eb_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['status'], name='ProjetoEsto_status_fe01b4_idx'),
        ),
    ]
