# Generated by Django 5.2.7 on 2026-05-07 15:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0062_alter_usuario_options_usuario_matricula_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciclomanutencao',
            options={'ordering': ['-data_inicio'], 'verbose_name': 'Ciclo de Manutenção', 'verbose_name_plural': 'Ciclos de Manutenção'},
        ),
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['-created_at'], 'verbose_name': 'Comentário', 'verbose_name_plural': 'Comentários'},
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['nome'], name='ProjetoEsto_nome_f99152_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['status'], name='ProjetoEsto_status_7ed6bd_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['item_consumo'], name='ProjetoEsto_item_co_0015aa_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['localidade'], name='ProjetoEsto_localid_c558dd_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['centro_custo'], name='ProjetoEsto_centro__1f4b32_idx'),
        ),
    ]
