# Generated by Django 5.2.7 on 2026-05-22 19:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0065_preventiva_data_pausada_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='coordenador',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Coordenador'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='gestor',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Gestor'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='responsavel',
            field=models.CharField(blank=True, help_text='Responsável hierárquico consolidado (Junção: Supervisor > Coordenador > Gestor)', max_length=150, null=True, verbose_name='Responsável'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='supervisor',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Supervisor'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['responsavel'], name='ProjetoEsto_respons_ea7436_idx'),
        ),
    ]
