# Generated by Django 5.2.7 on 2026-05-22 22:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0066_usuario_hierarquia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='diretor',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Diretor'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='diretor_geral',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Diretor Geral'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='responsavel',
            field=models.CharField(blank=True, help_text='Responsável hierárquico consolidado (Junção: Supervisor > Coordenador > Gestor > Diretor > Diretor Geral)', max_length=150, null=True, verbose_name='Responsável'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['diretor'], name='ProjetoEsto_diretor_cc29fb_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['diretor_geral'], name='ProjetoEsto_diretor_d91382_idx'),
        ),
    ]
