# Generated by Django 5.2.7 on 2026-05-24 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0071_corrigir_diretor_marcos_oliveira'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantaProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Planta')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('layout', models.JSONField(default=dict, help_text='Estrutura visual da planta: elementos, conexões e posições', verbose_name='Layout JSON')),
                ('imagem_fundo', models.ImageField(blank=True, help_text='Planta baixa ou croqui (PNG/JPG, máx. 10 MB)', null=True, upload_to='plantas/fundos/', verbose_name='Imagem de Fundo')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizador', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criador', to=settings.AUTH_USER_MODEL)),
                ('localidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantas', to='ProjetoEstoque.localidade', verbose_name='Localidade')),
            ],
            options={
                'verbose_name': 'Planta de Localidade',
                'verbose_name_plural': 'Plantas de Localidades',
                'ordering': ['localidade__local', 'nome'],
                'indexes': [models.Index(fields=['localidade'], name='ProjetoEsto_localid_8136ec_idx')],
            },
        ),
    ]
