# Generated by Django 5.2.7 on 2026-05-25 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0072_planta_projeto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='plantaprojeto',
            name='layout_version',
            field=models.PositiveIntegerField(default=1, verbose_name='Versão do Layout'),
        ),
        migrations.CreateModel(
            name='PlantaLayoutHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao', models.PositiveIntegerField()),
                ('layout', models.JSONField()),
                ('descricao', models.CharField(blank=True, max_length=200, verbose_name='Descrição')),
                ('salvo_em', models.DateTimeField(auto_now_add=True)),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_versoes', to='ProjetoEstoque.plantaprojeto')),
                ('salvo_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='layouts_salvos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Versão de Layout',
                'verbose_name_plural': 'Versões de Layout',
                'ordering': ['-versao'],
                'unique_together': {('planta', 'versao')},
            },
        ),
    ]
