# Generated by Django 5.2.7 on 2026-05-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0073_planta_layout_versioning'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventiva',
            name='data_agendamento',
            field=models.DateField(blank=True, help_text='Data explícita para a próxima execução. Sobrepõe o cálculo automático. Limpa após execução.', null=True, verbose_name='Data agendada'),
        ),
    ]
