# Generated by Django 5.2.7 on 2026-05-27 22:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0075_grupo_visualizador_tv'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='plantaprojeto',
            name='visualizadores_tv',
            field=models.ManyToManyField(blank=True, help_text="Usuários do grupo 'Visualizador TV' autorizados a ver esta planta no modo TV.", related_name='plantas_tv_autorizadas', to=settings.AUTH_USER_MODEL, verbose_name='Visualizadores TV'),
        ),
    ]
