# Generated by Django 5.2.7 on 2026-05-28 00:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0076_visualizadores_tv'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemStatusHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(blank=True, default='', max_length=20)),
                ('status_novo', models.CharField(max_length=20)),
                ('alterado_em', models.DateTimeField(auto_now_add=True)),
                ('alterado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_historico', to='ProjetoEstoque.item', verbose_name='Equipamento')),
            ],
            options={
                'verbose_name': 'Histórico de Status do Item',
                'verbose_name_plural': 'Históricos de Status de Itens',
                'ordering': ['-alterado_em'],
                'indexes': [models.Index(fields=['item', '-alterado_em'], name='ProjetoEsto_item_id_53abbe_idx')],
            },
        ),
    ]
