# Generated by Django 5.2.7 on 2026-05-28 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0078_item_prtg_historico'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='itemprtghistorico',
            new_name='ProjetoEsto_item_id_bb11b2_idx',
            old_name='projetoesto_item_prtg_idx',
        ),
    ]
