# Generated by Django 5.2.7 on 2026-06-02 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0080_configuracaosistema'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NinjaDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ninja_id', models.IntegerField(db_index=True, unique=True, verbose_name='ID NinjaOne')),
                ('display_name', models.CharField(max_length=255, verbose_name='Nome do dispositivo')),
                ('hostname', models.CharField(blank=True, max_length=255, verbose_name='Hostname / DNS')),
                ('serial_number', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Número de série')),
                ('os_name', models.CharField(blank=True, max_length=255, verbose_name='Sistema Operacional')),
                ('manufacturer', models.CharField(blank=True, max_length=255, verbose_name='Fabricante')),
                ('model_name', models.CharField(blank=True, max_length=255, verbose_name='Modelo')),
                ('processor', models.CharField(blank=True, max_length=255, verbose_name='Processador')),
                ('total_memory_mb', models.IntegerField(blank=True, null=True, verbose_name='Memória RAM (MB)')),
                ('ip_address', models.CharField(blank=True, max_length=50, verbose_name='Endereço IP')),
                ('last_contact', models.DateTimeField(blank=True, null=True, verbose_name='Último contato')),
                ('is_online', models.BooleanField(default=False, verbose_name='Online agora')),
                ('last_user', models.CharField(blank=True, max_length=255, verbose_name='Último usuário logado')),
                ('organization_name', models.CharField(blank=True, max_length=255, verbose_name='Organização')),
                ('node_class', models.CharField(blank=True, max_length=60, verbose_name='Tipo de dispositivo')),
                ('last_sync', models.DateTimeField(auto_now=True, verbose_name='Última sincronização')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizador', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criador', to=settings.AUTH_USER_MODEL)),
                ('item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ninja_device', to='ProjetoEstoque.item', verbose_name='Item vinculado (estoque)')),
            ],
            options={
                'verbose_name': 'Dispositivo NinjaOne',
                'verbose_name_plural': 'Dispositivos NinjaOne',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='NinjaDeviceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='Horário')),
                ('is_online', models.BooleanField(default=False, verbose_name='Online')),
                ('current_user', models.CharField(blank=True, max_length=255, verbose_name='Usuário logado')),
                ('ip_address', models.CharField(blank=True, max_length=50, verbose_name='IP')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='ProjetoEstoque.ninjadevice', verbose_name='Dispositivo')),
            ],
            options={
                'verbose_name': 'Snapshot NinjaOne',
                'verbose_name_plural': 'Snapshots NinjaOne',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='ninjadevice',
            index=models.Index(fields=['is_online'], name='ProjetoEsto_is_onli_9c680d_idx'),
        ),
        migrations.AddIndex(
            model_name='ninjadevice',
            index=models.Index(fields=['serial_number'], name='ProjetoEsto_serial__30c249_idx'),
        ),
        migrations.AddIndex(
            model_name='ninjadevicesnapshot',
            index=models.Index(fields=['device', '-timestamp'], name='ProjetoEsto_device__c1ef98_idx'),
        ),
        migrations.AddIndex(
            model_name='ninjadevicesnapshot',
            index=models.Index(fields=['timestamp'], name='ProjetoEsto_timesta_113c66_idx'),
        ),
        migrations.AddIndex(
            model_name='ninjadevicesnapshot',
            index=models.Index(fields=['device', 'is_online'], name='ProjetoEsto_device__62b4e1_idx'),
        ),
    ]
