# Generated by Django 5.2.7 on 2026-06-13 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0082_ninja_oauth_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='preventiva',
            name='tecnico',
            field=models.ForeignKey(blank=True, help_text='Usuário (equipe de TI) responsável por executar esta atividade.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preventivas_atribuidas', to=settings.AUTH_USER_MODEL, verbose_name='Técnico responsável'),
        ),
        migrations.AddField(
            model_name='preventivaexecucao',
            name='data_agendada',
            field=models.DateField(blank=True, null=True, verbose_name='Data agendada (no momento da execução)'),
        ),
        migrations.AddField(
            model_name='preventivaexecucao',
            name='no_prazo',
            field=models.BooleanField(default=True, help_text='True quando a execução ocorreu até a data agendada (ou sem agendamento).', verbose_name='Executada no prazo'),
        ),
        migrations.AddField(
            model_name='preventivaexecucao',
            name='tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execucoes_preventiva', to=settings.AUTH_USER_MODEL, verbose_name='Técnico'),
        ),
    ]
