# Generated by Django 5.2.7 on 2026-06-15 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0083_preventiva_tecnico_preventivaexecucao_data_agendada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventiva',
            name='foto_antes_2',
            field=models.ImageField(blank=True, null=True, upload_to='preventivas/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='preventiva',
            name='foto_depois_2',
            field=models.ImageField(blank=True, null=True, upload_to='preventivas/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='preventivaexecucao',
            name='foto_antes_2',
            field=models.ImageField(blank=True, null=True, upload_to='preventivas/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='preventivaexecucao',
            name='foto_depois_2',
            field=models.ImageField(blank=True, null=True, upload_to='preventivas/%Y/%m/'),
        ),
    ]
