# Generated by Django 5.2.7 on 2026-06-20 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0084_preventiva_foto_antes_2_preventiva_foto_depois_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ninjadevice',
            name='local',
            field=models.CharField(blank=True, db_index=True, max_length=120, verbose_name='Local / Site'),
        ),
        migrations.AlterField(
            model_name='ninjadevice',
            name='last_sync',
            field=models.DateTimeField(auto_now=True, verbose_name='Última importação'),
        ),
        migrations.AlterField(
            model_name='ninjadevice',
            name='ninja_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='ID NinjaOne'),
        ),
        migrations.DeleteModel(
            name='NinjaOAuthToken',
        ),
    ]
