# Generated by Django 5.2.7 on 2026-06-20 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0085_ninjadevice_local_alter_ninjadevice_last_sync_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NinjaLoginRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verificado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Verificado em')),
                ('device_user', models.CharField(blank=True, max_length=255, verbose_name='Login no dispositivo')),
                ('usuario_sistema_nome', models.CharField(blank=True, max_length=150, verbose_name='Colaborador atribuído (snapshot)')),
                ('usuario_detectado', models.CharField(blank=True, max_length=150, verbose_name='Colaborador detectado pelo login')),
                ('item_nome', models.CharField(blank=True, max_length=200, verbose_name='Item')),
                ('status', models.CharField(choices=[('confere', 'Confere'), ('divergente', 'Divergente'), ('sem_atribuicao', 'Sem atribuição no sistema'), ('sem_login', 'Sem login no dispositivo')], db_index=True, max_length=20, verbose_name='Status')),
                ('detalhe', models.CharField(blank=True, max_length=400, verbose_name='Detalhe')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_registros', to='ProjetoEstoque.ninjadevice', verbose_name='Dispositivo')),
                ('usuario_sistema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ninja_login_registros', to='ProjetoEstoque.usuario', verbose_name='Colaborador atribuído')),
            ],
            options={
                'verbose_name': 'Registro de login NinjaOne',
                'verbose_name_plural': 'Registros de login NinjaOne',
                'ordering': ['-verificado_em', '-id'],
                'indexes': [models.Index(fields=['device', '-verificado_em'], name='ProjetoEsto_device__03478f_idx'), models.Index(fields=['status'], name='ProjetoEsto_status_aba30b_idx')],
            },
        ),
    ]
