# Generated by Django 5.2.7 on 2026-06-21 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0086_ninjaloginregistro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaoitem',
            name='tipo_movimentacao',
            field=models.CharField(choices=[('transferencia', 'Transferência de dispositivo'), ('transferencia_equipamento', 'Transferência Equipamento'), ('baixa', 'Baixa'), ('entrada', 'Entrada'), ('envio_manutencao', 'Envio para Manutenção'), ('retorno_manutencao', 'Retorno de Manutenção'), ('outros', 'Outros')], max_length=30, verbose_name='Tipo de Movimentação'),
        ),
    ]
