# Generated by Django 5.2.7 on 2026-06-21 03:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0087_alter_movimentacaoitem_tipo_movimentacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemprtghistorico',
            options={'ordering': ['-registrado_em'], 'verbose_name': 'Histórico PRTG', 'verbose_name_plural': 'Históricos PRTG'},
        ),
        migrations.AddField(
            model_name='itemprtghistorico',
            name='device_grupo',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Grupo (PRTG)'),
        ),
        migrations.AddField(
            model_name='itemprtghistorico',
            name='device_host',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Host / IP'),
        ),
        migrations.AddField(
            model_name='itemprtghistorico',
            name='device_nome',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Device (PRTG)'),
        ),
        migrations.AlterField(
            model_name='itemprtghistorico',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prtg_historico', to='ProjetoEstoque.item', verbose_name='Equipamento'),
        ),
        migrations.AlterField(
            model_name='itemprtghistorico',
            name='prtg_objid',
            field=models.IntegerField(db_index=True, verbose_name='PRTG ObjID'),
        ),
        migrations.AlterField(
            model_name='itemprtghistorico',
            name='registrado_em',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='itemprtghistorico',
            index=models.Index(fields=['prtg_objid', '-registrado_em'], name='ProjetoEsto_prtg_ob_a545b5_idx'),
        ),
    ]
