# Generated by Django 5.2.7 on 2026-06-22 19:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0088_alter_itemprtghistorico_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KioskDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('token_hash', models.CharField(db_index=True, max_length=64)),
                ('serial', models.CharField(blank=True, db_index=True, default='', max_length=120, verbose_name='Número de série')),
                ('android_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('apelido', models.CharField(blank=True, default='', max_length=120, verbose_name='Apelido')),
                ('fabricante', models.CharField(blank=True, default='', max_length=80)),
                ('modelo', models.CharField(blank=True, default='', max_length=120)),
                ('android_versao', models.CharField(blank=True, default='', max_length=20, verbose_name='Versão Android')),
                ('app_versao', models.CharField(blank=True, default='', max_length=20, verbose_name='Versão do app')),
                ('ram_mb', models.IntegerField(blank=True, null=True, verbose_name='RAM (MB)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('wifi_only', models.BooleanField(default=True, verbose_name='Somente Wi-Fi')),
                ('apps_permitidos', models.JSONField(blank=True, default=list, verbose_name='Apps permitidos (packages)')),
                ('admin_pin_hash', models.CharField(blank=True, default='', max_length=255, verbose_name='Hash do PIN do TI')),
                ('intervalo_checkin_seg', models.IntegerField(default=300, verbose_name='Intervalo de check-in (s)')),
                ('mensagem_quiosque', models.CharField(blank=True, default='', max_length=200, verbose_name='Mensagem do quiosque')),
                ('config_versao', models.IntegerField(default=1, verbose_name='Versão da configuração')),
                ('ultima_latitude', models.FloatField(blank=True, null=True)),
                ('ultima_longitude', models.FloatField(blank=True, null=True)),
                ('ultima_precisao_m', models.FloatField(blank=True, null=True)),
                ('ultima_bateria', models.IntegerField(blank=True, null=True)),
                ('ultima_rede', models.CharField(blank=True, default='', max_length=20)),
                ('ultimo_checkin', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kiosk_devices', to='ProjetoEstoque.item', verbose_name='Equipamento vinculado')),
            ],
            options={
                'verbose_name': 'Dispositivo de Quiosque',
                'verbose_name_plural': 'Dispositivos de Quiosque',
                'ordering': ['-ultimo_checkin', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='KioskComando',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('bloquear', 'Bloquear dispositivo'), ('desbloquear', 'Desbloquear dispositivo'), ('mensagem', 'Exibir mensagem'), ('atualizar_config', 'Atualizar configuração'), ('reiniciar_app', 'Reiniciar aplicativo')], max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('entregue', 'Entregue'), ('executado', 'Executado'), ('falhou', 'Falhou')], db_index=True, default='pendente', max_length=12)),
                ('detalhe', models.CharField(blank=True, default='', max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('entregue_em', models.DateTimeField(blank=True, null=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kiosk_comandos', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comandos', to='ProjetoEstoque.kioskdevice')),
            ],
            options={
                'verbose_name': 'Comando de Quiosque',
                'verbose_name_plural': 'Comandos de Quiosque',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='KioskCheckin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('precisao_m', models.FloatField(blank=True, null=True)),
                ('bateria', models.IntegerField(blank=True, null=True)),
                ('carregando', models.BooleanField(default=False)),
                ('rede', models.CharField(blank=True, default='', max_length=20)),
                ('online', models.BooleanField(default=True)),
                ('registrado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='ProjetoEstoque.kioskdevice')),
            ],
            options={
                'verbose_name': 'Check-in de Quiosque',
                'verbose_name_plural': 'Check-ins de Quiosque',
                'ordering': ['-registrado_em'],
            },
        ),
        migrations.CreateModel(
            name='KioskMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=16, unique=True, verbose_name='Código')),
                ('descricao', models.CharField(blank=True, default='', max_length=120, verbose_name='Descrição')),
                ('usado', models.BooleanField(default=False)),
                ('usado_em', models.DateTimeField(blank=True, null=True)),
                ('expira_em', models.DateTimeField(blank=True, null=True, verbose_name='Expira em')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kiosk_matriculas', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matricula', to='ProjetoEstoque.kioskdevice')),
            ],
            options={
                'verbose_name': 'Matrícula de Quiosque',
                'verbose_name_plural': 'Matrículas de Quiosque',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='kioskdevice',
            index=models.Index(fields=['ativo', '-ultimo_checkin'], name='ProjetoEsto_ativo_b0a293_idx'),
        ),
        migrations.AddIndex(
            model_name='kioskcomando',
            index=models.Index(fields=['device', 'status'], name='ProjetoEsto_device__7edcfc_idx'),
        ),
        migrations.AddIndex(
            model_name='kioskcheckin',
            index=models.Index(fields=['device', '-registrado_em'], name='ProjetoEsto_device__b3cf43_idx'),
        ),
    ]
