# Generated by Django 5.2.7 on 2026-06-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0089_kioskdevice_kioskcomando_kioskcheckin_kioskmatricula_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kioskcheckin',
            name='coletado_em',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Coletado em'),
        ),
        migrations.AddIndex(
            model_name='kioskcheckin',
            index=models.Index(fields=['device', '-coletado_em'], name='ProjetoEsto_device__e23362_idx'),
        ),
    ]
