# Generated by Django 5.2.7 on 2026-06-26 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0092_grupo_fornecedor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('aguardando_recebimento', 'Aguardando recebimento'), ('recebido', 'Recebido pelo fornecedor'), ('em_avaliacao', 'Em avaliação'), ('em_reparo', 'Em reparo'), ('reparado', 'Reparado — aguardando devolução'), ('sem_reparo', 'Sem reparo — troca'), ('substituto_enviado', 'Substituto enviado — aguardando recebimento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='aguardando_recebimento', max_length=30)),
                ('diagnostico', models.TextField(blank=True, null=True, verbose_name='Diagnóstico do fornecedor')),
                ('chamado', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nº Chamado')),
                ('finalizada_em', models.DateTimeField(blank=True, null=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizador', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criador', to=settings.AUTH_USER_MODEL)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_manutencao', to='ProjetoEstoque.fornecedor', verbose_name='Fornecedor responsável')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens_manutencao', to='ProjetoEstoque.item', verbose_name='Equipamento')),
                ('item_substituto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_substituicao', to='ProjetoEstoque.item', verbose_name='Equipamento substituto')),
                ('movimentacao_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_manutencao', to='ProjetoEstoque.movimentacaoitem', verbose_name='Movimentação de envio')),
            ],
            options={
                'verbose_name': 'Ordem de Manutenção',
                'verbose_name_plural': 'Ordens de Manutenção',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrdemManutencaoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('aguardando_recebimento', 'Aguardando recebimento'), ('recebido', 'Recebido pelo fornecedor'), ('em_avaliacao', 'Em avaliação'), ('em_reparo', 'Em reparo'), ('reparado', 'Reparado — aguardando devolução'), ('sem_reparo', 'Sem reparo — troca'), ('substituto_enviado', 'Substituto enviado — aguardando recebimento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], max_length=30, verbose_name='Status registrado')),
                ('observacao', models.TextField(blank=True, null=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizador', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criador', to=settings.AUTH_USER_MODEL)),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='ProjetoEstoque.ordemmanutencao')),
            ],
            options={
                'verbose_name': 'Evento de Manutenção',
                'verbose_name_plural': 'Eventos de Manutenção',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='ordemmanutencao',
            index=models.Index(fields=['status'], name='ProjetoEsto_status_196ae4_idx'),
        ),
        migrations.AddIndex(
            model_name='ordemmanutencao',
            index=models.Index(fields=['fornecedor'], name='ProjetoEsto_fornece_eda46f_idx'),
        ),
    ]
