# Generated by Django 5.2.7 on 2026-06-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0093_ordemmanutencao_ordemmanutencaoevento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemmanutencao',
            name='substituto_contrato',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Contrato de substituição'),
        ),
        migrations.AddField(
            model_name='ordemmanutencao',
            name='substituto_data',
            field=models.DateField(blank=True, null=True, verbose_name='Data da substituição'),
        ),
        migrations.AddField(
            model_name='ordemmanutencao',
            name='substituto_valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor da substituição'),
        ),
    ]
