# Generated by Django 5.2.7 on 2026-06-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0094_ordemmanutencao_substituto_contrato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemmanutencao',
            name='substituto_locado',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', max_length=3, verbose_name='Substituto entra como locação?'),
        ),
        migrations.AlterField(
            model_name='ordemmanutencao',
            name='status',
            field=models.CharField(choices=[('aguardando_recebimento', 'Aguardando recebimento'), ('recebido', 'Recebido pelo fornecedor'), ('em_avaliacao', 'Em avaliação'), ('em_reparo', 'Em reparo'), ('reparado', 'Reparo concluído'), ('devolvido', 'Devolvido ao cliente — aguardando recebimento'), ('sem_reparo', 'Sem reparo — troca'), ('substituto_enviado', 'Substituto enviado — aguardando recebimento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='aguardando_recebimento', max_length=30),
        ),
        migrations.AlterField(
            model_name='ordemmanutencaoevento',
            name='status',
            field=models.CharField(choices=[('aguardando_recebimento', 'Aguardando recebimento'), ('recebido', 'Recebido pelo fornecedor'), ('em_avaliacao', 'Em avaliação'), ('em_reparo', 'Em reparo'), ('reparado', 'Reparo concluído'), ('devolvido', 'Devolvido ao cliente — aguardando recebimento'), ('sem_reparo', 'Sem reparo — troca'), ('substituto_enviado', 'Substituto enviado — aguardando recebimento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], max_length=30, verbose_name='Status registrado'),
        ),
    ]
