# Generated by Django 5.2.7 on 2026-06-26 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0095_ordemmanutencao_substituto_locado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemmanutencao',
            name='devolucao_localidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_devolucao', to='ProjetoEstoque.localidade', verbose_name='Localidade de devolução'),
        ),
        migrations.CreateModel(
            name='LocacaoPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valor_mensal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, help_text='Vazio = período em andamento', null=True)),
                ('motivo_fim', models.CharField(blank=True, help_text='Status que encerrou o período (pausado/defeito).', max_length=20, null=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizador', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criador', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locacao_periodos', to='ProjetoEstoque.item')),
            ],
            options={
                'verbose_name': 'Período de Locação',
                'verbose_name_plural': 'Períodos de Locação',
                'ordering': ['-data_inicio', '-id'],
                'indexes': [models.Index(fields=['item', 'data_fim'], name='ProjetoEsto_item_id_248b86_idx')],
            },
        ),
    ]
