# Generated by Django 5.2.7 on 2026-06-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0096_ordemmanutencao_devolucao_localidade_locacaoperiodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemmanutencao',
            name='reparo_valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor do reparo realizado'),
        ),
    ]
