# Generated by Django 5.2.7 on 2026-06-26 23:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0097_ordemmanutencao_reparo_valor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='compartilhado',
            field=models.BooleanField(default=False, help_text='Se marcado, o equipamento pode ficar vinculado a vários colaboradores ao mesmo tempo (cada um com seu termo de responsabilidade). Se não, segue o fluxo padrão de detentor único.', verbose_name='Pode ser compartilhado?'),
        ),
        migrations.CreateModel(
            name='ItemColaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True, verbose_name='Vínculo ativo')),
                ('data_vinculo', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Vinculado em')),
                ('data_devolucao', models.DateTimeField(blank=True, null=True, verbose_name='Devolvido em')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizador', to=settings.AUTH_USER_MODEL)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_compartilhados', to='ProjetoEstoque.usuario', verbose_name='Colaborador')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criador', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_colaborador', to='ProjetoEstoque.item', verbose_name='Equipamento')),
                ('movimentacao_devolucao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vinculos_encerrados', to='ProjetoEstoque.movimentacaoitem', verbose_name='Movimentação de devolução')),
                ('movimentacao_entrega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vinculos_abertos', to='ProjetoEstoque.movimentacaoitem', verbose_name='Movimentação de entrega')),
            ],
            options={
                'verbose_name': 'Vínculo de Equipamento Compartilhado',
                'verbose_name_plural': 'Vínculos de Equipamentos Compartilhados',
                'ordering': ['-data_vinculo'],
                'indexes': [models.Index(fields=['item', 'ativo'], name='ProjetoEsto_item_id_c6f91c_idx'), models.Index(fields=['colaborador', 'ativo'], name='ProjetoEsto_colabor_0796b1_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('ativo', True)), fields=('item', 'colaborador'), name='uniq_vinculo_ativo_item_colaborador')],
            },
        ),
    ]
