# Generated by Django 5.2.7 on 2026-06-28 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0099_preventivaexecucao_apontamento_horas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemmanutencao',
            name='aprovado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_manutencao_decididas', to=settings.AUTH_USER_MODEL, verbose_name='Decisão do TI por'),
        ),
        migrations.AddField(
            model_name='ordemmanutencao',
            name='decisao_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da decisão do TI'),
        ),
        migrations.AddField(
            model_name='ordemmanutencao',
            name='valor_avaliacao_tecnica',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor da avaliação técnica'),
        ),
        migrations.AddField(
            model_name='ordemmanutencao',
            name='valor_conserto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor do conserto'),
        ),
        migrations.AddField(
            model_name='ordemmanutencao',
            name='valor_orcamento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Orçamento do reparo (proposto)'),
        ),
        migrations.AddField(
            model_name='ordemmanutencao',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor total (conserto + extras)'),
        ),
        migrations.AlterField(
            model_name='ordemmanutencao',
            name='status',
            field=models.CharField(choices=[('aguardando_recebimento', 'Aguardando recebimento'), ('recebido', 'Recebido pelo fornecedor'), ('em_avaliacao', 'Em avaliação'), ('aguardando_aprovacao', 'Aguardando aprovação do TI'), ('aprovado', 'Reparo aprovado'), ('reprovado', 'Reparo reprovado'), ('em_reparo', 'Em reparo'), ('reparado', 'Reparo concluído'), ('devolvido', 'Devolvido ao cliente — aguardando recebimento'), ('sem_reparo', 'Sem reparo — troca'), ('substituto_enviado', 'Substituto enviado — aguardando recebimento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='aguardando_recebimento', max_length=30),
        ),
        migrations.AlterField(
            model_name='ordemmanutencaoevento',
            name='status',
            field=models.CharField(choices=[('aguardando_recebimento', 'Aguardando recebimento'), ('recebido', 'Recebido pelo fornecedor'), ('em_avaliacao', 'Em avaliação'), ('aguardando_aprovacao', 'Aguardando aprovação do TI'), ('aprovado', 'Reparo aprovado'), ('reprovado', 'Reparo reprovado'), ('em_reparo', 'Em reparo'), ('reparado', 'Reparo concluído'), ('devolvido', 'Devolvido ao cliente — aguardando recebimento'), ('sem_reparo', 'Sem reparo — troca'), ('substituto_enviado', 'Substituto enviado — aguardando recebimento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], max_length=30, verbose_name='Status registrado'),
        ),
        migrations.CreateModel(
            name='OrdemManutencaoAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arquivo', models.FileField(upload_to='manutencao/nf/%Y/%m/', verbose_name='Arquivo')),
                ('origem', models.CharField(choices=[('fornecedor', 'Fornecedor'), ('ti', 'TI')], default='ti', max_length=12, verbose_name='Origem')),
                ('descricao', models.CharField(blank=True, default='', max_length=200, verbose_name='Descrição')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizador', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criador', to=settings.AUTH_USER_MODEL)),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='ProjetoEstoque.ordemmanutencao')),
            ],
            options={
                'verbose_name': 'Anexo de Manutenção',
                'verbose_name_plural': 'Anexos de Manutenção',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
