# Generated by Django 5.2.7 on 2026-06-29 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0100_ordemmanutencao_aprovado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kioskcheckin',
            name='ssid',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='SSID'),
        ),
        migrations.AddField(
            model_name='kioskdevice',
            name='mac',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='MAC Wi-Fi'),
        ),
    ]
