# Generated by Django 5.2.7 on 2026-07-02 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0101_kioskcheckin_ssid_kioskdevice_mac'),
    ]

    operations = [
        migrations.AddField(
            model_name='kioskdevice',
            name='apps_atualizado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inventário de apps atualizado em'),
        ),
        migrations.AddField(
            model_name='kioskdevice',
            name='apps_hash',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Hash do inventário de apps'),
        ),
        migrations.CreateModel(
            name='KioskDeviceApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pkg', models.CharField(max_length=255, verbose_name='Pacote')),
                ('nome', models.CharField(blank=True, default='', max_length=255, verbose_name='Nome')),
                ('sistema', models.BooleanField(default=False, verbose_name='App de sistema')),
                ('visto_em', models.DateTimeField(auto_now=True, verbose_name='Visto em')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='ProjetoEstoque.kioskdevice')),
            ],
            options={
                'verbose_name': 'App de Dispositivo de Quiosque',
                'verbose_name_plural': 'Apps de Dispositivos de Quiosque',
                'ordering': ['sistema', 'nome', 'pkg'],
                'indexes': [models.Index(fields=['device', 'sistema'], name='ProjetoEsto_device__2ce717_idx')],
                'unique_together': {('device', 'pkg')},
            },
        ),
    ]
