# Generated by Django 5.2.7 on 2026-07-02 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0102_kioskdevice_apps_atualizado_em_kioskdevice_apps_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemmanutencao',
            name='garantia_dias',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Prazo de garantia (dias)'),
        ),
        migrations.AddField(
            model_name='ordemmanutencao',
            name='garantia_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Fim da garantia'),
        ),
        migrations.AddField(
            model_name='ordemmanutencao',
            name='garantia_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Início da garantia (recebimento do TI)'),
        ),
        migrations.AddField(
            model_name='ordemmanutencao',
            name='tem_garantia',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', max_length=3, verbose_name='Reparo/troca com garantia?'),
        ),
    ]
