# Generated by Django 5.2.7 on 2026-07-05 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0103_ordemmanutencao_garantia_dias_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroSeguranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('login_ok', 'Login bem-sucedido'), ('login_falha', 'Falha de login'), ('logout', 'Logout'), ('acesso_negado', 'Acesso negado')], max_length=20)),
                ('username', models.CharField(blank=True, help_text='Usuário informado na tentativa', max_length=254)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=400)),
                ('caminho', models.CharField(blank=True, max_length=200)),
                ('suspeito', models.BooleanField(default=False)),
                ('detalhe', models.CharField(blank=True, max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_seguranca', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de segurança',
                'verbose_name_plural': 'Registros de segurança',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['tipo', 'criado_em'], name='ProjetoEsto_tipo_df376a_idx'), models.Index(fields=['username', 'criado_em'], name='ProjetoEsto_usernam_1f848f_idx'), models.Index(fields=['ip', 'criado_em'], name='ProjetoEsto_ip_ba27f3_idx'), models.Index(fields=['suspeito', 'criado_em'], name='ProjetoEsto_suspeit_7f5e50_idx')],
            },
        ),
    ]
