# Generated by Django 5.2.7 on 2026-07-05 11:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0104_registroseguranca'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NovidadeSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('versao', models.CharField(blank=True, help_text='Ex.: 4.1.0', max_length=20)),
                ('data', models.DateField(default=django.utils.timezone.localdate, help_text='Data da atualização')),
                ('tipo', models.CharField(choices=[('novo', 'Novo'), ('melhoria', 'Melhoria'), ('correcao', 'Correção')], default='novo', max_length=12)),
                ('titulo', models.CharField(max_length=140)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True, help_text='Desmarque para ocultar sem excluir')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizador', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Novidade do sistema',
                'verbose_name_plural': 'Novidades do sistema',
                'ordering': ['-data', '-id'],
                'indexes': [models.Index(fields=['ativo', '-data'], name='ProjetoEsto_ativo_fc4413_idx')],
            },
        ),
    ]
