# Generated by Django 5.2.7 on 2026-07-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0107_ordemmanutencao_substituto_tempo_meses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('backup', 'Backup'), ('manutencao', 'Manutenção'), ('defeito', 'Defeito'), ('pausado', 'Pausado'), ('descarte', 'Descarte')], default='ativo', max_length=15),
        ),
        migrations.AlterField(
            model_name='movimentacaoitem',
            name='status_retorno',
            field=models.CharField(blank=True, choices=[('ativo', 'Ativo'), ('backup', 'Backup'), ('manutencao', 'Manutenção'), ('defeito', 'Defeito'), ('pausado', 'Pausado'), ('descarte', 'Descarte')], max_length=15, null=True, verbose_name='Status Retorno'),
        ),
        migrations.AlterField(
            model_name='movimentacaoitem',
            name='status_transferencia',
            field=models.CharField(blank=True, choices=[('ativo', 'Ativo'), ('backup', 'Backup'), ('manutencao', 'Manutenção'), ('defeito', 'Defeito'), ('pausado', 'Pausado'), ('descarte', 'Descarte')], max_length=15, null=True, verbose_name='Novo Status'),
        ),
    ]
