# Generated by Django 5.2.7 on 2026-07-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0108_alter_item_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemmanutencao',
            name='status',
            field=models.CharField(choices=[('aguardando_recebimento', 'Aguardando recebimento'), ('recebido', 'Recebido pelo fornecedor'), ('em_avaliacao', 'Em avaliação'), ('aguardando_aprovacao', 'Aguardando aprovação do TI'), ('aprovado', 'Reparo aprovado'), ('reprovado', 'Reparo reprovado'), ('em_reparo', 'Em reparo'), ('reparado', 'Reparo concluído'), ('devolvido', 'Devolvido ao cliente — aguardando recebimento'), ('sem_reparo', 'Sem reparo — troca'), ('substituto_enviado', 'Substituto enviado — aguardando recebimento'), ('sem_condicoes', 'Sem condições de reparo — aguardando descarte'), ('descarte_local_solicitado', 'Descarte local solicitado — aguardando aprovação do TI'), ('descarte_local_aprovado', 'Descarte local aprovado — aguardando o fornecedor'), ('descartado', 'Descartado'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='aguardando_recebimento', max_length=30),
        ),
        migrations.AlterField(
            model_name='ordemmanutencaoevento',
            name='status',
            field=models.CharField(choices=[('aguardando_recebimento', 'Aguardando recebimento'), ('recebido', 'Recebido pelo fornecedor'), ('em_avaliacao', 'Em avaliação'), ('aguardando_aprovacao', 'Aguardando aprovação do TI'), ('aprovado', 'Reparo aprovado'), ('reprovado', 'Reparo reprovado'), ('em_reparo', 'Em reparo'), ('reparado', 'Reparo concluído'), ('devolvido', 'Devolvido ao cliente — aguardando recebimento'), ('sem_reparo', 'Sem reparo — troca'), ('substituto_enviado', 'Substituto enviado — aguardando recebimento'), ('sem_condicoes', 'Sem condições de reparo — aguardando descarte'), ('descarte_local_solicitado', 'Descarte local solicitado — aguardando aprovação do TI'), ('descarte_local_aprovado', 'Descarte local aprovado — aguardando o fornecedor'), ('descartado', 'Descartado'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], max_length=30, verbose_name='Status registrado'),
        ),
    ]
