# Generated by Django 5.2.7 on 2026-07-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0110_alter_ordemmanutencao_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemmanutencao',
            name='troca_antecipada',
            field=models.BooleanField(default=False, verbose_name='Troca antecipada'),
        ),
        migrations.AlterField(
            model_name='ordemmanutencao',
            name='status',
            field=models.CharField(choices=[('aguardando_recebimento', 'Aguardando recebimento'), ('recebido', 'Recebido pelo fornecedor'), ('em_avaliacao', 'Em avaliação'), ('aguardando_aprovacao', 'Aguardando aprovação do TI'), ('aprovado', 'Reparo aprovado'), ('reprovado', 'Reparo reprovado'), ('em_reparo', 'Em reparo'), ('reparado', 'Reparo concluído'), ('devolvido', 'Devolvido ao cliente — aguardando recebimento'), ('sem_reparo', 'Sem reparo — troca'), ('substituto_enviado', 'Substituto enviado — aguardando recebimento'), ('sem_condicoes', 'Sem condições de reparo — aguardando devolução'), ('devolvido_descarte', 'Devolvido para descarte — aguardando recebimento do TI'), ('descarte_local_solicitado', 'Descarte local solicitado — aguardando aprovação do TI'), ('descarte_local_aprovado', 'Descarte local aprovado — aguardando o fornecedor'), ('descartado', 'Descartado'), ('troca_ant_sub_enviado', 'Troca antecipada — substituto a caminho'), ('troca_ant_sub_recebido', 'Troca antecipada — substituto recebido, enviar o defeituoso'), ('troca_ant_def_enviado', 'Troca antecipada — defeituoso enviado ao fornecedor'), ('troca_ant_def_recebido', 'Troca antecipada — defeituoso recebido, aguardando proposta'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='aguardando_recebimento', max_length=30),
        ),
        migrations.AlterField(
            model_name='ordemmanutencaoevento',
            name='status',
            field=models.CharField(choices=[('aguardando_recebimento', 'Aguardando recebimento'), ('recebido', 'Recebido pelo fornecedor'), ('em_avaliacao', 'Em avaliação'), ('aguardando_aprovacao', 'Aguardando aprovação do TI'), ('aprovado', 'Reparo aprovado'), ('reprovado', 'Reparo reprovado'), ('em_reparo', 'Em reparo'), ('reparado', 'Reparo concluído'), ('devolvido', 'Devolvido ao cliente — aguardando recebimento'), ('sem_reparo', 'Sem reparo — troca'), ('substituto_enviado', 'Substituto enviado — aguardando recebimento'), ('sem_condicoes', 'Sem condições de reparo — aguardando devolução'), ('devolvido_descarte', 'Devolvido para descarte — aguardando recebimento do TI'), ('descarte_local_solicitado', 'Descarte local solicitado — aguardando aprovação do TI'), ('descarte_local_aprovado', 'Descarte local aprovado — aguardando o fornecedor'), ('descartado', 'Descartado'), ('troca_ant_sub_enviado', 'Troca antecipada — substituto a caminho'), ('troca_ant_sub_recebido', 'Troca antecipada — substituto recebido, enviar o defeituoso'), ('troca_ant_def_enviado', 'Troca antecipada — defeituoso enviado ao fornecedor'), ('troca_ant_def_recebido', 'Troca antecipada — defeituoso recebido, aguardando proposta'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], max_length=30, verbose_name='Status registrado'),
        ),
    ]
