# Generated by Django 5.2.7 on 2026-07-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0111_ordemmanutencao_troca_antecipada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('mensagem', models.TextField(blank=True)),
                ('url', models.CharField(blank=True, max_length=300)),
                ('icone', models.CharField(default='fa-bell', max_length=40)),
                ('categoria', models.CharField(default='geral', max_length=40)),
                ('lida', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['lida', '-created_at'], name='ProjetoEsto_lida_62e555_idx')],
            },
        ),
    ]
