# Generated by Django 5.2.7 on 2026-07-07 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0112_notificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='ProjetoEstoque.fornecedor'),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='lida_fornecedor',
            field=models.BooleanField(default=False, verbose_name='Lida (fornecedor)'),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='portal_url',
            field=models.CharField(blank=True, help_text='Link usado no sino do Portal do Fornecedor', max_length=300),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='lida',
            field=models.BooleanField(default=False, verbose_name='Lida (interno/TI)'),
        ),
        migrations.AddIndex(
            model_name='notificacao',
            index=models.Index(fields=['fornecedor', 'lida_fornecedor', '-created_at'], name='ProjetoEsto_fornece_9016c4_idx'),
        ),
    ]
