# Generated by Django 5.2.7 on 2026-07-08 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0113_notificacao_fornecedor_notificacao_lida_fornecedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilfornecedor',
            name='notificar_defeito_email',
            field=models.BooleanField(default=True, help_text='Quando ativo, este login recebe um e-mail sempre que um equipamento do fornecedor for marcado como Defeito.', verbose_name='Notificar por e-mail (equipamento em Defeito)'),
        ),
    ]
