# Generated by Django 5.2.7 on 2026-07-08 23:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0114_perfilfornecedor_notificar_defeito_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CanalNotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(max_length=60, unique=True)),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.CharField(blank=True, default='', max_length=255)),
                ('categoria', models.CharField(blank=True, default='', max_length=60)),
                ('icone', models.CharField(blank=True, default='fa-bell', max_length=40)),
                ('tipo_destinatarios', models.CharField(choices=[('fixo', 'Lista fixa (editável aqui)'), ('dinamico', 'Definido em outra tela do sistema')], default='fixo', max_length=10)),
                ('destino_gerenciado_em', models.CharField(blank=True, default='', max_length=255)),
                ('origem_disparo', models.CharField(blank=True, default='', max_length=255)),
                ('ativo', models.BooleanField(default=True, verbose_name='Notificação ativa')),
                ('destinatarios_customizados', models.TextField(blank=True, default='', help_text='E-mails separados por vírgula. Vazio = usa o padrão do sistema (.env).', verbose_name='Destinatários customizados')),
                ('ultimo_envio', models.DateTimeField(blank=True, null=True)),
                ('total_envios', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Canal de Notificação',
                'verbose_name_plural': 'Canais de Notificação',
                'ordering': ['categoria', 'nome'],
            },
        ),
    ]
