# Generated by Django 5.2.7 on 2026-07-08 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0115_canalnotificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='canalnotificacao',
            name='destinatarios_customizados_ativo',
            field=models.BooleanField(default=False, help_text='Quando ativo, `destinatarios_customizados` é a lista definitiva (mesmo vazia — nesse caso ninguém recebe). Quando inativo, usa o padrão do sistema (.env). Ativado automaticamente ao editar a lista ou remover uma pessoa individualmente.', verbose_name='Usa lista customizada'),
        ),
    ]
