# Generated by Django 5.2.7 on 2026-07-10 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0116_canalnotificacao_destinatarios_customizados_ativo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemManutencaoOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.PositiveIntegerField(help_text='1, 2, 3... (auto-incrementado por ordem de criação)', verbose_name='Número da proposta')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor proposto')),
                ('status', models.CharField(choices=[('proposto', 'Proposto'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default='proposto', max_length=12, verbose_name='Status da proposta')),
                ('motivo_rejeicao', models.TextField(blank=True, null=True, verbose_name='Motivo da rejeição (se reprovado)')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizador', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criador', to=settings.AUTH_USER_MODEL)),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orcamentos', to='ProjetoEstoque.ordemmanutencao', verbose_name='Ordem de Manutenção')),
            ],
            options={
                'verbose_name': 'Orçamento de Manutenção',
                'verbose_name_plural': 'Orçamentos de Manutenção',
                'ordering': ['numero'],
                'indexes': [models.Index(fields=['ordem', 'numero'], name='ProjetoEsto_ordem_i_7ebb47_idx')],
            },
        ),
    ]
