# Generated by Django 5.2.7 on 2026-07-10 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0117_ordemmanutencaoorcamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemmanutencaoorcamento',
            name='status',
            field=models.CharField(choices=[('proposto', 'Enviado para análise'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default='proposto', max_length=12, verbose_name='Status da proposta'),
        ),
        migrations.CreateModel(
            name='LoteManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do lote')),
                ('data', models.DateField(verbose_name='Data do lote')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizador', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criador', to=settings.AUTH_USER_MODEL)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_manutencao', to='ProjetoEstoque.fornecedor', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'Lote de Manutenção',
                'verbose_name_plural': 'Lotes de Manutenção',
                'ordering': ['-data', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='ordemmanutencao',
            name='lote_manutencao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens', to='ProjetoEstoque.lotemanutencao', verbose_name='Lote de manutenção'),
        ),
        migrations.AddIndex(
            model_name='lotemanutencao',
            index=models.Index(fields=['fornecedor', 'data'], name='ProjetoEsto_fornece_90b448_idx'),
        ),
    ]
