# Generated by Django 5.2.7 on 2026-07-11 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0118_alter_ordemmanutencaoorcamento_status_lotemanutencao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KioskInstaladorLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('nome_arquivo', models.CharField(max_length=255, verbose_name='Arquivo')),
                ('expira_em', models.DateTimeField(verbose_name='Expira em')),
                ('revogado', models.BooleanField(default=False)),
                ('downloads', models.PositiveIntegerField(default=0)),
                ('ultimo_download_em', models.DateTimeField(blank=True, null=True)),
                ('ultimo_download_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kiosk_instaladores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Link de Instalador de Quiosque',
                'verbose_name_plural': 'Links de Instalador de Quiosque',
                'ordering': ['-criado_em'],
            },
        ),
    ]
