# Generated by Django 5.2.7 on 2026-07-12 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0119_kiosk_instalador_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('backup', 'Backup'), ('manutencao', 'Manutenção'), ('defeito', 'Defeito'), ('pausado', 'Pausado'), ('descarte', 'Descarte'), ('devolvido', 'Devolvido (Locação)')], default='ativo', max_length=15),
        ),
        migrations.AlterField(
            model_name='movimentacaoitem',
            name='status_retorno',
            field=models.CharField(blank=True, choices=[('ativo', 'Ativo'), ('backup', 'Backup'), ('manutencao', 'Manutenção'), ('defeito', 'Defeito'), ('pausado', 'Pausado'), ('descarte', 'Descarte'), ('devolvido', 'Devolvido (Locação)')], max_length=15, null=True, verbose_name='Status Retorno'),
        ),
        migrations.AlterField(
            model_name='movimentacaoitem',
            name='status_transferencia',
            field=models.CharField(blank=True, choices=[('ativo', 'Ativo'), ('backup', 'Backup'), ('manutencao', 'Manutenção'), ('defeito', 'Defeito'), ('pausado', 'Pausado'), ('descarte', 'Descarte'), ('devolvido', 'Devolvido (Locação)')], max_length=15, null=True, verbose_name='Novo Status'),
        ),
        migrations.AlterField(
            model_name='movimentacaoitem',
            name='tipo_movimentacao',
            field=models.CharField(choices=[('transferencia', 'Transferência de dispositivo'), ('transferencia_equipamento', 'Transferência Equipamento'), ('baixa', 'Baixa'), ('entrada', 'Entrada'), ('envio_manutencao', 'Envio para Manutenção'), ('retorno_manutencao', 'Retorno de Manutenção'), ('separacao_envio', 'Separação para Envio'), ('separacao_devolucao', 'Separação para Devolução'), ('devolucao_locacao', 'Devolução de Locação'), ('outros', 'Outros')], max_length=30, verbose_name='Tipo de Movimentação'),
        ),
        migrations.CreateModel(
            name='LoteSeparacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do lote')),
                ('tipo', models.CharField(choices=[('envio', 'Separado para Envio'), ('devolucao', 'Separado para Devolução')], max_length=10, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('aberto', 'Em separação'), ('enviado', 'Enviado'), ('cancelado', 'Removido da separação')], db_index=True, default='aberto', max_length=12)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('enviado_em', models.DateTimeField(blank=True, null=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizador', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criador', to=settings.AUTH_USER_MODEL)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_separacao', to='ProjetoEstoque.fornecedor', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'Lote de Separação',
                'verbose_name_plural': 'Lotes de Separação',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SeparacaoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('envio', 'Separado para Envio'), ('devolucao', 'Separado para Devolução')], max_length=10, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('aberto', 'Em separação'), ('enviado', 'Enviado'), ('cancelado', 'Removido da separação')], db_index=True, default='aberto', max_length=12)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('enviado_em', models.DateTimeField(blank=True, null=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizador', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criador', to=settings.AUTH_USER_MODEL)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_separados', to='ProjetoEstoque.fornecedor', verbose_name='Fornecedor')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='separacoes', to='ProjetoEstoque.item', verbose_name='Equipamento')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens', to='ProjetoEstoque.loteseparacao', verbose_name='Lote de separação')),
                ('movimentacao_despacho', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ProjetoEstoque.movimentacaoitem', verbose_name='Movimentação de despacho')),
                ('movimentacao_entrada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ProjetoEstoque.movimentacaoitem', verbose_name='Movimentação de entrada em separação')),
            ],
            options={
                'verbose_name': 'Item em Separação',
                'verbose_name_plural': 'Itens em Separação',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='loteseparacao',
            index=models.Index(fields=['tipo', 'status'], name='ProjetoEsto_tipo_fe6180_idx'),
        ),
        migrations.AddIndex(
            model_name='separacaoitem',
            index=models.Index(fields=['tipo', 'status'], name='ProjetoEsto_tipo_d285be_idx'),
        ),
        migrations.AddConstraint(
            model_name='separacaoitem',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'aberto')), fields=('item',), name='uniq_item_separacao_aberta'),
        ),
    ]
