# Generated by Django 5.2.7 on 2026-07-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0120_separacao_itens'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loteseparacao',
            options={'ordering': ['-created_at'], 'verbose_name': 'Lote de Remessa', 'verbose_name_plural': 'Lotes de Remessa'},
        ),
        migrations.AlterModelOptions(
            name='separacaoitem',
            options={'ordering': ['-created_at'], 'verbose_name': 'Item em Remessa', 'verbose_name_plural': 'Itens em Remessa'},
        ),
        migrations.AlterField(
            model_name='loteseparacao',
            name='tipo',
            field=models.CharField(choices=[('envio', 'Remessa para Envio'), ('devolucao', 'Remessa para Devolução')], max_length=10, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='movimentacaoitem',
            name='tipo_movimentacao',
            field=models.CharField(choices=[('transferencia', 'Transferência de dispositivo'), ('transferencia_equipamento', 'Transferência Equipamento'), ('baixa', 'Baixa'), ('entrada', 'Entrada'), ('envio_manutencao', 'Envio para Manutenção'), ('retorno_manutencao', 'Retorno de Manutenção'), ('separacao_envio', 'Remessa para Envio'), ('separacao_devolucao', 'Remessa para Devolução'), ('devolucao_locacao', 'Devolução de Locação'), ('outros', 'Outros')], max_length=30, verbose_name='Tipo de Movimentação'),
        ),
        migrations.AlterField(
            model_name='separacaoitem',
            name='tipo',
            field=models.CharField(choices=[('envio', 'Remessa para Envio'), ('devolucao', 'Remessa para Devolução')], max_length=10, verbose_name='Tipo'),
        ),
    ]
