# Generated by Django 5.2.7 on 2026-07-12 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0121_renomear_remessa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoFiscalRemessa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('envio', 'Remessa para Envio'), ('devolucao', 'Remessa para Devolução')], max_length=10, verbose_name='Tipo')),
                ('email_enviado', models.BooleanField(default=False, verbose_name='E-mail enviado ao Fiscal')),
                ('destinatarios_envio', models.TextField(blank=True, default='', help_text='Snapshot dos e-mails para quem foi enviado (separados por vírgula).', verbose_name='Destinatários no momento do envio')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizador', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criador', to=settings.AUTH_USER_MODEL)),
                ('itens', models.ManyToManyField(related_name='documentos_fiscais', to='ProjetoEstoque.separacaoitem', verbose_name='Itens do documento')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_fiscais', to='ProjetoEstoque.loteseparacao', verbose_name='Lote de origem')),
            ],
            options={
                'verbose_name': 'Documento Fiscal de Remessa',
                'verbose_name_plural': 'Documentos Fiscais de Remessa',
                'ordering': ['-created_at'],
            },
        ),
    ]
