# Generated by Django 5.2.7 on 2026-07-13 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0122_documento_fiscal_remessa'),
    ]

    operations = [
        migrations.AddField(
            model_name='kioskdevice',
            name='armazenamento_livre_mb',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Armazenamento livre (MB)'),
        ),
        migrations.AddField(
            model_name='kioskdevice',
            name='armazenamento_total_mb',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Armazenamento total (MB)'),
        ),
        migrations.AddField(
            model_name='kioskdevice',
            name='armazenamento_usado_mb',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Armazenamento usado (MB)'),
        ),
        migrations.AddField(
            model_name='kioskdevice',
            name='ram_livre_mb',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='RAM livre (MB)'),
        ),
        migrations.AddField(
            model_name='kioskdevice',
            name='ram_pouca',
            field=models.BooleanField(default=False, verbose_name='Pouca RAM (sinalizado pelo Android)'),
        ),
        migrations.AddField(
            model_name='kioskdevice',
            name='ram_total_mb',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='RAM total (MB)'),
        ),
        migrations.AddField(
            model_name='kioskdevice',
            name='ram_usada_mb',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='RAM usada (MB)'),
        ),
        migrations.AddField(
            model_name='kioskdeviceapp',
            name='atualizado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Atualizado em (no aparelho)'),
        ),
        migrations.AddField(
            model_name='kioskdeviceapp',
            name='versao',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Versão'),
        ),
        migrations.AddField(
            model_name='kioskdeviceapp',
            name='versao_codigo',
            field=models.BigIntegerField(default=0, verbose_name='Código da versão'),
        ),
    ]
