# Generated by Django 5.2.7 on 2026-07-14 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0123_kioskdevice_armazenamento_livre_mb_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemmanutencao',
            name='status',
            field=models.CharField(choices=[('aguardando_recebimento', 'Aguardando recebimento'), ('recebido', 'Recebido pelo fornecedor'), ('em_avaliacao', 'Em avaliação'), ('aguardando_aprovacao', 'Aguardando aprovação do TI'), ('aprovado', 'Reparo aprovado'), ('reprovado', 'Reparo reprovado'), ('em_reparo', 'Em reparo'), ('reparado', 'Reparo concluído'), ('devolvido', 'Devolvido ao cliente — aguardando recebimento'), ('sem_reparo', 'Sem reparo — troca'), ('substituto_enviado', 'Substituto enviado — aguardando recebimento'), ('sem_condicoes', 'Sem condições de reparo — aguardando devolução'), ('devolvido_descarte', 'Devolvido para descarte — aguardando recebimento do TI'), ('descarte_local_solicitado', 'Descarte local solicitado — aguardando aprovação do TI'), ('descarte_local_aprovado', 'Descarte local aprovado — aguardando o fornecedor'), ('descartado', 'Descartado'), ('troca_ant_sub_enviado', 'Troca antecipada — substituto a caminho'), ('troca_ant_sub_recebido', 'Troca antecipada — substituto recebido, enviar o defeituoso'), ('troca_ant_def_enviado', 'Troca antecipada — defeituoso enviado ao fornecedor'), ('troca_ant_def_recebido', 'Troca antecipada — defeituoso recebido, aguardando proposta'), ('troca_ant_aguardando_aprovacao', 'Troca antecipada — proposta aguardando aprovação do TI'), ('troca_ant_aprovado', 'Troca antecipada — proposta aprovada'), ('troca_ant_reprovado', 'Troca antecipada — proposta reprovada'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='aguardando_recebimento', max_length=30),
        ),
        migrations.AlterField(
            model_name='ordemmanutencaoevento',
            name='status',
            field=models.CharField(choices=[('aguardando_recebimento', 'Aguardando recebimento'), ('recebido', 'Recebido pelo fornecedor'), ('em_avaliacao', 'Em avaliação'), ('aguardando_aprovacao', 'Aguardando aprovação do TI'), ('aprovado', 'Reparo aprovado'), ('reprovado', 'Reparo reprovado'), ('em_reparo', 'Em reparo'), ('reparado', 'Reparo concluído'), ('devolvido', 'Devolvido ao cliente — aguardando recebimento'), ('sem_reparo', 'Sem reparo — troca'), ('substituto_enviado', 'Substituto enviado — aguardando recebimento'), ('sem_condicoes', 'Sem condições de reparo — aguardando devolução'), ('devolvido_descarte', 'Devolvido para descarte — aguardando recebimento do TI'), ('descarte_local_solicitado', 'Descarte local solicitado — aguardando aprovação do TI'), ('descarte_local_aprovado', 'Descarte local aprovado — aguardando o fornecedor'), ('descartado', 'Descartado'), ('troca_ant_sub_enviado', 'Troca antecipada — substituto a caminho'), ('troca_ant_sub_recebido', 'Troca antecipada — substituto recebido, enviar o defeituoso'), ('troca_ant_def_enviado', 'Troca antecipada — defeituoso enviado ao fornecedor'), ('troca_ant_def_recebido', 'Troca antecipada — defeituoso recebido, aguardando proposta'), ('troca_ant_aguardando_aprovacao', 'Troca antecipada — proposta aguardando aprovação do TI'), ('troca_ant_aprovado', 'Troca antecipada — proposta aprovada'), ('troca_ant_reprovado', 'Troca antecipada — proposta reprovada'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], max_length=30, verbose_name='Status registrado'),
        ),
        migrations.CreateModel(
            name='LoteEnvioFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do lote')),
                ('status', models.CharField(choices=[('aberto', 'Em organização'), ('enviado', 'Enviado ao TI'), ('cancelado', 'Cancelado')], db_index=True, default='aberto', max_length=10)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('enviado_em', models.DateTimeField(blank=True, null=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizador', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criador', to=settings.AUTH_USER_MODEL)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_envio', to='ProjetoEstoque.fornecedor', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'Lote de Envio do Fornecedor',
                'verbose_name_plural': 'Lotes de Envio do Fornecedor',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoteEnvioFornecedorAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arquivo', models.FileField(upload_to='lote_envio_fornecedor/nf/%Y/%m/', verbose_name='Arquivo')),
                ('origem', models.CharField(choices=[('fornecedor', 'Fornecedor'), ('ti', 'TI')], default='fornecedor', max_length=12, verbose_name='Origem')),
                ('descricao', models.CharField(blank=True, default='', max_length=200, verbose_name='Descrição')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizador', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criador', to=settings.AUTH_USER_MODEL)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='ProjetoEstoque.loteenviofornecedor')),
            ],
            options={
                'verbose_name': 'Anexo do Lote de Envio',
                'verbose_name_plural': 'Anexos do Lote de Envio',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LoteEnvioFornecedorItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('troca_antecipada', 'Troca antecipada'), ('equipamento_novo', 'Equipamento novo')], max_length=20, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('rascunho', 'Em organização (rascunho)'), ('enviado', 'Enviado ao TI'), ('recebido', 'Recebido pelo TI'), ('cancelado', 'Cancelado')], db_index=True, default='rascunho', max_length=10)),
                ('sub_modelo', models.CharField(blank=True, default='', max_length=200, verbose_name='Modelo do substituto')),
                ('sub_serie', models.CharField(blank=True, default='', max_length=200, verbose_name='Série do substituto')),
                ('sub_marca', models.CharField(blank=True, default='', max_length=200, verbose_name='Marca do substituto')),
                ('sub_data_contrato', models.DateField(blank=True, null=True, verbose_name='Data de contrato do equipamento')),
                ('novo_nome', models.CharField(blank=True, default='', max_length=200, verbose_name='Nome/Modelo')),
                ('novo_numero_serie', models.CharField(blank=True, default='', max_length=200, verbose_name='Número de série')),
                ('novo_marca', models.CharField(blank=True, default='', max_length=200, verbose_name='Marca')),
                ('novo_modelo', models.CharField(blank=True, default='', max_length=200, verbose_name='Modelo')),
                ('novo_locado', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', max_length=3, verbose_name='Entra como locação?')),
                ('novo_valor', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor')),
                ('novo_contrato', models.CharField(blank=True, default='', max_length=200, verbose_name='Contrato')),
                ('novo_tempo_contrato_meses', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tempo de contrato (meses)')),
                ('enviado_em', models.DateTimeField(blank=True, null=True)),
                ('recebido_em', models.DateTimeField(blank=True, null=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizador', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criador', to=settings.AUTH_USER_MODEL)),
                ('item_defeituoso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rascunhos_troca_antecipada', to='ProjetoEstoque.item', verbose_name='Equipamento com defeito')),
                ('item_resultado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ProjetoEstoque.item', verbose_name='Equipamento gerado')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='ProjetoEstoque.loteenviofornecedor', verbose_name='Lote de envio')),
                ('novo_categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ProjetoEstoque.categoria', verbose_name='Categoria')),
                ('novo_centro_custo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ProjetoEstoque.centrocusto', verbose_name='Centro de custo')),
                ('novo_localidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ProjetoEstoque.localidade', verbose_name='Localidade')),
                ('novo_subtipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ProjetoEstoque.subtipo', verbose_name='Subtipo')),
                ('ordem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ProjetoEstoque.ordemmanutencao', verbose_name='Ordem de manutenção gerada')),
            ],
            options={
                'verbose_name': 'Item do Lote de Envio',
                'verbose_name_plural': 'Itens do Lote de Envio',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='loteenviofornecedor',
            index=models.Index(fields=['fornecedor', 'status'], name='ProjetoEsto_fornece_c69282_idx'),
        ),
        migrations.AddConstraint(
            model_name='loteenviofornecedor',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'aberto')), fields=('fornecedor',), name='uniq_fornecedor_lote_envio_aberto'),
        ),
        migrations.AddIndex(
            model_name='loteenviofornecedoritem',
            index=models.Index(fields=['tipo', 'status'], name='ProjetoEsto_tipo_7a7a3e_idx'),
        ),
        migrations.AddConstraint(
            model_name='loteenviofornecedoritem',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'rascunho'), ('tipo', 'troca_antecipada')), fields=('item_defeituoso',), name='uniq_item_defeituoso_rascunho_aberto'),
        ),
    ]
