# Generated by Django 5.2.7 on 2026-07-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0124_lote_envio_fornecedor_e_troca_ant_aprovacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='loteenviofornecedoritem',
            name='novo_cobranca_proximo_ano',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', help_text='Se Sim, o período de locação começa em 1º de janeiro do ano seguinte à confirmação de recebimento pelo TI. Se Não, começa na data em que o fornecedor cadastrou o equipamento neste lote.', max_length=3, verbose_name='Cobrança do aluguel só a partir do próximo ano?'),
        ),
        migrations.AddField(
            model_name='loteenviofornecedoritem',
            name='novo_pmb',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', max_length=3, verbose_name='PMB?'),
        ),
    ]
