# Generated by Django 5.2.7 on 2026-07-14 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0125_lote_envio_pmb_cobranca_proximo_ano'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='loteenviofornecedor',
            name='uniq_fornecedor_lote_envio_aberto',
        ),
    ]
