# Generated by Django 5.2.7 on 2026-07-15 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0126_remover_constraint_lote_envio_aberto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loteenviofornecedoritem',
            name='localidade_devolucao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ProjetoEstoque.localidade', verbose_name='Localidade de devolução'),
        ),
        migrations.AddField(
            model_name='loteenviofornecedoritem',
            name='valor_avaliacao_tecnica',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Só se aplica quando a OS foi reprovada (devolução sem reparo).', max_digits=12, null=True, verbose_name='Valor da avaliação técnica'),
        ),
        migrations.AlterField(
            model_name='loteenviofornecedoritem',
            name='tipo',
            field=models.CharField(choices=[('troca_antecipada', 'Troca antecipada'), ('equipamento_novo', 'Equipamento novo'), ('reparo_concluido', 'Reparo concluído')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AddConstraint(
            model_name='loteenviofornecedoritem',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'rascunho'), ('tipo', 'reparo_concluido')), fields=('ordem',), name='uniq_ordem_reparo_rascunho_aberto'),
        ),
    ]
