# Generated by Django 5.2.7 on 2026-07-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0127_loteenviofornecedoritem_localidade_devolucao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemmanutencaoorcamento',
            name='tipo',
            field=models.CharField(choices=[('reparo', 'Orçamento de reparo'), ('troca', 'Contrato do equipamento substituto (troca)'), ('descarte', 'Avaliação de descarte (devolução ao TI)'), ('descarte_local', 'Avaliação de descarte local')], default='reparo', help_text='De qual desfecho esta proposta faz parte (reparo, troca ou descarte).', max_length=20, verbose_name='Tipo de avaliação'),
        ),
        migrations.AlterField(
            model_name='ordemmanutencao',
            name='status',
            field=models.CharField(choices=[('aguardando_recebimento', 'Aguardando recebimento'), ('recebido', 'Recebido pelo fornecedor'), ('em_avaliacao', 'Em avaliação'), ('aguardando_aprovacao', 'Aguardando aprovação do TI'), ('aprovado', 'Reparo aprovado'), ('reprovado', 'Reparo reprovado'), ('em_reparo', 'Em reparo'), ('reparado', 'Reparo concluído'), ('devolvido', 'Devolvido ao cliente — aguardando recebimento'), ('sem_reparo', 'Sem reparo — troca'), ('troca_aguardando_aprovacao', 'Troca — contrato do substituto aguardando aprovação do TI'), ('troca_aprovada', 'Troca — contrato aprovado pelo TI'), ('troca_reprovada', 'Troca — contrato reprovado pelo TI'), ('substituto_enviado', 'Substituto enviado — aguardando recebimento'), ('sem_condicoes', 'Sem condições de reparo — aguardando devolução'), ('descarte_avaliacao_aprovada', 'Descarte — avaliação aprovada pelo TI'), ('descarte_avaliacao_reprovada', 'Descarte — avaliação reprovada pelo TI'), ('devolvido_descarte', 'Devolvido para descarte — aguardando recebimento do TI'), ('descarte_local_solicitado', 'Descarte local solicitado — aguardando aprovação do TI'), ('descarte_local_aprovado', 'Descarte local aprovado — aguardando o fornecedor'), ('descartado', 'Descartado'), ('troca_ant_sub_enviado', 'Troca antecipada — substituto a caminho'), ('troca_ant_sub_recebido', 'Troca antecipada — substituto recebido, enviar o defeituoso'), ('troca_ant_def_enviado', 'Troca antecipada — defeituoso enviado ao fornecedor'), ('troca_ant_def_recebido', 'Troca antecipada — defeituoso recebido, aguardando proposta'), ('troca_ant_aguardando_aprovacao', 'Troca antecipada — proposta aguardando aprovação do TI'), ('troca_ant_aprovado', 'Troca antecipada — proposta aprovada'), ('troca_ant_reprovado', 'Troca antecipada — proposta reprovada'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='aguardando_recebimento', max_length=30),
        ),
        migrations.AlterField(
            model_name='ordemmanutencaoevento',
            name='status',
            field=models.CharField(choices=[('aguardando_recebimento', 'Aguardando recebimento'), ('recebido', 'Recebido pelo fornecedor'), ('em_avaliacao', 'Em avaliação'), ('aguardando_aprovacao', 'Aguardando aprovação do TI'), ('aprovado', 'Reparo aprovado'), ('reprovado', 'Reparo reprovado'), ('em_reparo', 'Em reparo'), ('reparado', 'Reparo concluído'), ('devolvido', 'Devolvido ao cliente — aguardando recebimento'), ('sem_reparo', 'Sem reparo — troca'), ('troca_aguardando_aprovacao', 'Troca — contrato do substituto aguardando aprovação do TI'), ('troca_aprovada', 'Troca — contrato aprovado pelo TI'), ('troca_reprovada', 'Troca — contrato reprovado pelo TI'), ('substituto_enviado', 'Substituto enviado — aguardando recebimento'), ('sem_condicoes', 'Sem condições de reparo — aguardando devolução'), ('descarte_avaliacao_aprovada', 'Descarte — avaliação aprovada pelo TI'), ('descarte_avaliacao_reprovada', 'Descarte — avaliação reprovada pelo TI'), ('devolvido_descarte', 'Devolvido para descarte — aguardando recebimento do TI'), ('descarte_local_solicitado', 'Descarte local solicitado — aguardando aprovação do TI'), ('descarte_local_aprovado', 'Descarte local aprovado — aguardando o fornecedor'), ('descartado', 'Descartado'), ('troca_ant_sub_enviado', 'Troca antecipada — substituto a caminho'), ('troca_ant_sub_recebido', 'Troca antecipada — substituto recebido, enviar o defeituoso'), ('troca_ant_def_enviado', 'Troca antecipada — defeituoso enviado ao fornecedor'), ('troca_ant_def_recebido', 'Troca antecipada — defeituoso recebido, aguardando proposta'), ('troca_ant_aguardando_aprovacao', 'Troca antecipada — proposta aguardando aprovação do TI'), ('troca_ant_aprovado', 'Troca antecipada — proposta aprovada'), ('troca_ant_reprovado', 'Troca antecipada — proposta reprovada'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], max_length=30, verbose_name='Status registrado'),
        ),
    ]
