# Generated by Django 5.2.7 on 2026-07-16 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0129_ordemmanutencao_substituto_modelo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kioskdevice',
            name='app_versao_codigo',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Código da versão do app'),
        ),
        migrations.AddField(
            model_name='kioskdevice',
            name='atualizacao_motivo',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Motivo do bloqueio da atualização'),
        ),
        migrations.AddField(
            model_name='kioskdevice',
            name='atualizacao_status',
            field=models.CharField(blank=True, choices=[('em_dia', 'Em dia'), ('baixando', 'Baixando'), ('instalando', 'Instalando'), ('bloqueada', 'Bloqueada')], default='', max_length=12, verbose_name='Status da auto-atualização'),
        ),
    ]
