# Generated by Django 5.2.7 on 2026-07-17 16:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0130_kioskdevice_atualizacao_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='preventivaexecucao',
            name='tecnicos_auxiliares',
            field=models.ManyToManyField(blank=True, help_text='Outros técnicos que participaram desta execução junto com o responsável.', related_name='execucoes_preventiva_auxiliar', to=settings.AUTH_USER_MODEL, verbose_name='Técnicos auxiliares'),
        ),
    ]
