# Generated by Django 5.2.7 on 2026-07-17 19:17

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0131_preventivaexecucao_tecnicos_auxiliares'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'base_manager_name': 'all_objects', 'verbose_name': 'Item / Equipamento', 'verbose_name_plural': 'Itens / Equipamentos'},
        ),
        migrations.AlterModelManagers(
            name='item',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='excluido',
            field=models.BooleanField(db_index=True, default=False, help_text='Item removido das listagens e seletores. Histórico vinculado é preservado.', verbose_name='Excluído'),
        ),
        migrations.AddField(
            model_name='item',
            name='excluido_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Excluído em'),
        ),
        migrations.AddField(
            model_name='item',
            name='excluido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por'),
        ),
        migrations.AddField(
            model_name='movimentacaoitem',
            name='revertida',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Revertida'),
        ),
        migrations.AddField(
            model_name='movimentacaoitem',
            name='revertida_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Revertida em'),
        ),
        migrations.AddField(
            model_name='movimentacaoitem',
            name='revertida_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Revertida por'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['excluido'], name='ProjetoEsto_excluid_bac93c_idx'),
        ),
    ]
