# Generated by Django 5.2.7 on 2026-07-18 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0132_soft_delete_item_e_reversao_movimentacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='kioskcheckin',
            name='mac_em_uso',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='MAC em uso'),
        ),
        migrations.AddField(
            model_name='kioskcheckin',
            name='wifi_banda_ghz',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Banda (GHz)'),
        ),
        migrations.AddField(
            model_name='kioskcheckin',
            name='wifi_frequencia_mhz',
            field=models.IntegerField(blank=True, null=True, verbose_name='Frequência do canal (MHz)'),
        ),
        migrations.AddField(
            model_name='kioskcheckin',
            name='wifi_nivel',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nível de sinal (0-4)'),
        ),
        migrations.AddField(
            model_name='kioskcheckin',
            name='wifi_rssi_dbm',
            field=models.IntegerField(blank=True, null=True, verbose_name='RSSI Wi-Fi (dBm)'),
        ),
        migrations.AddField(
            model_name='kioskcheckin',
            name='wifi_velocidade_mbps',
            field=models.IntegerField(blank=True, null=True, verbose_name='Velocidade do link (Mbps)'),
        ),
        migrations.AddField(
            model_name='kioskdevice',
            name='telemetria_wifi',
            field=models.BooleanField(default=False, verbose_name='Telemetria de sinal Wi-Fi'),
        ),
        migrations.AddField(
            model_name='kioskdevice',
            name='ultima_mac_em_uso',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='MAC em uso (última leitura)'),
        ),
        migrations.AddField(
            model_name='kioskdevice',
            name='wifi_mac_politica',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Política de MAC (última leitura)'),
        ),
        migrations.AddField(
            model_name='kioskdevice',
            name='wifi_rede_provisionada',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Provisionamento de rede (última leitura)'),
        ),
        migrations.AddField(
            model_name='kioskdevice',
            name='wifi_senha',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Senha da rede provisionada'),
        ),
        migrations.AddField(
            model_name='kioskdevice',
            name='wifi_ssid',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='SSID da rede provisionada'),
        ),
    ]
