# Generated by Django 5.2.7 on 2026-07-19 19:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0133_kiosk_wifi_telemetria_e_provisionamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('compra', 'Compra'), ('estoque', 'Estoque')], max_length=10, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('enviada_aprovacao', 'Solicitação Enviada para Aprovação'), ('aprovada', 'Solicitação Aprovada'), ('nao_aprovada', 'Solicitação Não Aprovada'), ('pausada', 'Solicitação Pausada'), ('com_erro', 'Solicitação com erro'), ('cancelada', 'Solicitação Cancelada')], db_index=True, default='rascunho', max_length=20)),
                ('numero_datasul', models.CharField(blank=True, db_index=True, help_text='Preenchido manualmente quando a requisição já existir no Datasul. Sem integração automática.', max_length=30, null=True, verbose_name='Número da Requisição (Datasul)')),
                ('numero_paradigma', models.CharField(blank=True, max_length=30, null=True, verbose_name='Número no Paradigma')),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('status_anterior_pausa', models.CharField(blank=True, choices=[('rascunho', 'Rascunho'), ('enviada_aprovacao', 'Solicitação Enviada para Aprovação'), ('aprovada', 'Solicitação Aprovada'), ('nao_aprovada', 'Solicitação Não Aprovada'), ('pausada', 'Solicitação Pausada'), ('com_erro', 'Solicitação com erro'), ('cancelada', 'Solicitação Cancelada')], max_length=20, null=True, verbose_name='Status antes de pausar')),
                ('enviada_em', models.DateTimeField(blank=True, null=True)),
                ('decidida_em', models.DateTimeField(blank=True, null=True, verbose_name='Aprovada/Reprovada em')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizador', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criador', to=settings.AUTH_USER_MODEL)),
                ('decidida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicoes_decididas', to=settings.AUTH_USER_MODEL, verbose_name='Aprovada/Reprovada por')),
            ],
            options={
                'verbose_name': 'Requisição',
                'verbose_name_plural': 'Requisições',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequisicaoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('compra', 'Compra'), ('estoque', 'Estoque')], max_length=10, verbose_name='Tipo')),
                ('codigo', models.CharField(blank=True, help_text='Código no Datasul, se já existir. Pode ficar em branco enquanto é só uma ideia.', max_length=60, null=True, verbose_name='Código')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('quantidade', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('nao_cadastrado', 'Item não cadastrado'), ('nao_solicitado', 'Item não solicitado'), ('solicitado', 'Item Solicitado'), ('pausado', 'Item pausado'), ('reprovado', 'Item reprovado')], db_index=True, default='nao_cadastrado', max_length=15)),
                ('justificativa', models.TextField(blank=True, null=True, verbose_name='Justificativa / motivo do pedido')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizador', to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_requisicao', to='ProjetoEstoque.categoria', verbose_name='Categoria')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criador', to=settings.AUTH_USER_MODEL)),
                ('item_vinculado', models.ForeignKey(blank=True, help_text='Vincula a um item já controlado por lote (mostra quantidade disponível). Deixe em branco para cadastro livre.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicoes_kanban', to='ProjetoEstoque.item', verbose_name='Item / Equipamento (opcional)')),
                ('requisicao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens', to='ProjetoEstoque.requisicao', verbose_name='Requisição')),
            ],
            options={
                'verbose_name': 'Item de Requisição',
                'verbose_name_plural': 'Itens de Requisição',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComentarioRequisicaoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('texto', models.TextField()),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizador', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criador', to=settings.AUTH_USER_MODEL)),
                ('requisicao_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='ProjetoEstoque.requisicaoitem', verbose_name='Item de Requisição')),
            ],
            options={
                'verbose_name': 'Comentário do Item de Requisição',
                'verbose_name_plural': 'Comentários do Item de Requisição',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='requisicao',
            index=models.Index(fields=['status'], name='ProjetoEsto_status_bf6802_idx'),
        ),
        migrations.AddIndex(
            model_name='requisicao',
            index=models.Index(fields=['tipo', 'status'], name='ProjetoEsto_tipo_15aeb7_idx'),
        ),
        migrations.AddIndex(
            model_name='requisicao',
            index=models.Index(fields=['numero_datasul'], name='ProjetoEsto_numero__525028_idx'),
        ),
        migrations.AddIndex(
            model_name='requisicaoitem',
            index=models.Index(fields=['status'], name='ProjetoEsto_status_0e886a_idx'),
        ),
        migrations.AddIndex(
            model_name='requisicaoitem',
            index=models.Index(fields=['requisicao', 'status'], name='ProjetoEsto_requisi_91b64a_idx'),
        ),
        migrations.AddIndex(
            model_name='requisicaoitem',
            index=models.Index(fields=['tipo', 'status'], name='ProjetoEsto_tipo_f687f2_idx'),
        ),
    ]
