# Generated by Django 5.2.7 on 2026-07-19 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0135_seed_categorias_requisicoes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicaoitem',
            name='retirado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Retirado em'),
        ),
        migrations.AddField(
            model_name='requisicaoitem',
            name='retirado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_requisicao_retirados', to=settings.AUTH_USER_MODEL, verbose_name='Retirado por'),
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('solicitada', 'Solicitação Solicitada'), ('enviada_aprovacao', 'Solicitação Enviada para Aprovação'), ('aprovada', 'Solicitação Aprovada'), ('nao_aprovada', 'Solicitação Não Aprovada'), ('pausada', 'Solicitação Pausada'), ('com_erro', 'Solicitação com erro'), ('cancelada', 'Solicitação Cancelada')], db_index=True, default='rascunho', max_length=20),
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='status_anterior_pausa',
            field=models.CharField(blank=True, choices=[('rascunho', 'Rascunho'), ('solicitada', 'Solicitação Solicitada'), ('enviada_aprovacao', 'Solicitação Enviada para Aprovação'), ('aprovada', 'Solicitação Aprovada'), ('nao_aprovada', 'Solicitação Não Aprovada'), ('pausada', 'Solicitação Pausada'), ('com_erro', 'Solicitação com erro'), ('cancelada', 'Solicitação Cancelada')], max_length=20, null=True, verbose_name='Status antes de pausar'),
        ),
        migrations.AlterField(
            model_name='requisicaoitem',
            name='status',
            field=models.CharField(choices=[('nao_cadastrado', 'Item não cadastrado'), ('nao_solicitado', 'Item não solicitado'), ('solicitado', 'Item Solicitado'), ('pausado', 'Item pausado'), ('reprovado', 'Item reprovado'), ('retirado', 'Item Retirado')], db_index=True, default='nao_cadastrado', max_length=15),
        ),
    ]
