# Generated by Django 5.2.7 on 2026-07-19 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0136_requisicaoitem_retirado_em_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicao',
            name='solicitada_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Solicitada em'),
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('solicitada', 'Solicitada'), ('enviada_aprovacao', 'Enviada para Aprovação'), ('aprovada', 'Aprovada'), ('nao_aprovada', 'Não Aprovada'), ('pausada', 'Pausada'), ('com_erro', 'Com Erro'), ('cancelada', 'Cancelada')], db_index=True, default='rascunho', max_length=20),
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='status_anterior_pausa',
            field=models.CharField(blank=True, choices=[('rascunho', 'Rascunho'), ('solicitada', 'Solicitada'), ('enviada_aprovacao', 'Enviada para Aprovação'), ('aprovada', 'Aprovada'), ('nao_aprovada', 'Não Aprovada'), ('pausada', 'Pausada'), ('com_erro', 'Com Erro'), ('cancelada', 'Cancelada')], max_length=20, null=True, verbose_name='Status antes de pausar'),
        ),
        migrations.CreateModel(
            name='ItemPadraoDatasul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=60, unique=True, verbose_name='Código (Datasul)')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, help_text='Itens inativos somem do seletor do formulário, mas continuam no catálogo.', verbose_name='Ativo')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizador', to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_padrao_datasul', to='ProjetoEstoque.categoria', verbose_name='Categoria')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item Padrão (Datasul)',
                'verbose_name_plural': 'Itens Padrão (Datasul)',
                'ordering': ['descricao'],
                'indexes': [models.Index(fields=['ativo'], name='ProjetoEsto_ativo_50802e_idx')],
            },
        ),
    ]
