# Generated by Django 5.2.7 on 2026-07-20 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0137_requisicao_solicitada_em_alter_requisicao_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('backup', 'Backup'), ('estoque', 'Estoque'), ('manutencao', 'Manutenção'), ('defeito', 'Defeito'), ('pausado', 'Pausado'), ('descarte', 'Descarte'), ('devolvido', 'Devolvido (Locação)')], default='ativo', max_length=15),
        ),
        migrations.AlterField(
            model_name='movimentacaoitem',
            name='status_retorno',
            field=models.CharField(blank=True, choices=[('ativo', 'Ativo'), ('backup', 'Backup'), ('estoque', 'Estoque'), ('manutencao', 'Manutenção'), ('defeito', 'Defeito'), ('pausado', 'Pausado'), ('descarte', 'Descarte'), ('devolvido', 'Devolvido (Locação)')], max_length=15, null=True, verbose_name='Status Retorno'),
        ),
        migrations.AlterField(
            model_name='movimentacaoitem',
            name='status_transferencia',
            field=models.CharField(blank=True, choices=[('ativo', 'Ativo'), ('backup', 'Backup'), ('estoque', 'Estoque'), ('manutencao', 'Manutenção'), ('defeito', 'Defeito'), ('pausado', 'Pausado'), ('descarte', 'Descarte'), ('devolvido', 'Devolvido (Locação)')], max_length=15, null=True, verbose_name='Novo Status'),
        ),
    ]
