# Generated by Django 5.2.7 on 2026-07-20 00:18
#
# Item de consumo com status "Backup" não tem lógica de negócio (backup é
# spare de equipamento, não faz sentido para toner/cabo/bateria em estoque).
# Corrige dados existentes para o novo status "Estoque" — daqui pra frente o
# formulário de cadastro/edição já impede selecionar "Backup" pra consumo.

from django.db import migrations


def consumo_backup_para_estoque(apps, schema_editor):
    Item = apps.get_model('ProjetoEstoque', 'Item')
    Item.objects.filter(item_consumo='sim', status='backup').update(status='estoque')


def estoque_para_backup(apps, schema_editor):
    Item = apps.get_model('ProjetoEstoque', 'Item')
    Item.objects.filter(item_consumo='sim', status='estoque').update(status='backup')


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0138_adiciona_status_estoque'),
    ]

    operations = [
        migrations.RunPython(consumo_backup_para_estoque, estoque_para_backup),
    ]
