# Generated by Django 5.2.7 on 2026-07-20 01:02
#
# Corrige Item.quantidade divergente da soma de ItemLote.quantidade_disponivel.
# Causa raiz (corrigida em views/equipamentos.py, item_update): a tela de
# Editar Equipamento sobrescrevia Item.quantidade com o total do ÚNICO lote
# sendo editado (o mais recente), descartando a contribuição dos demais lotes
# do item — invisível em itens de lote único, mas corrompe o saldo assim que
# o item passa a ter mais de um lote (cada vez mais comum com o recebimento
# de compra vinculado a estoque). Não há valor "correto anterior" pra
# reverter — a reversão é um no-op.

from django.db import migrations
from django.db.models import Sum


def reconciliar_quantidade_com_lotes(apps, schema_editor):
    Item = apps.get_model('ProjetoEstoque', 'Item')
    itens = Item.objects.filter(tem_lote=True).annotate(
        soma_disponivel=Sum('vinculos_lote__quantidade_disponivel')
    )
    for item in itens:
        correto = item.soma_disponivel or 0
        if correto != (item.quantidade or 0):
            item.quantidade = correto
            item.save(update_fields=['quantidade'])


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0139_migra_consumo_backup_para_estoque'),
    ]

    operations = [
        migrations.RunPython(reconciliar_quantidade_com_lotes, migrations.RunPython.noop),
    ]
