# Generated by Django 5.2.7 on 2026-07-23 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0140_reconcilia_quantidade_item_com_lotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='numero_nf',
            field=models.CharField(blank=True, help_text='Nota fiscal do item — válido tanto para item próprio quanto locado.', max_length=60, null=True, verbose_name='Número da NF'),
        ),
    ]
