# Generated by Django 5.2.7 on 2026-07-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0141_adiciona_numero_nf_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='kioskdevice',
            name='permite_reiniciar',
            field=models.BooleanField(default=False, verbose_name='Permite reiniciar (botão no app)'),
        ),
        migrations.AddField(
            model_name='kioskdevice',
            name='permite_desligar',
            field=models.BooleanField(default=False, verbose_name='Permite desligar (botão no app, best-effort)'),
        ),
        migrations.AddField(
            model_name='kioskdevice',
            name='limpeza_cache_automatica',
            field=models.BooleanField(default=False, verbose_name='Limpeza automática de cache do app'),
        ),
        migrations.AddField(
            model_name='kioskdevice',
            name='cache_app_mb',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Cache do app (MB)'),
        ),
        migrations.AddField(
            model_name='kioskdevice',
            name='dados_app_mb',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Dados do app (MB)'),
        ),
    ]
