# Generated by Django 5.2.7 on 2026-07-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0142_kiosk_gates_reiniciar_desligar_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='kioskdevice',
            name='permite_limpar_apps_terceiros',
            field=models.BooleanField(default=False, verbose_name='Permite limpar cache/dados dos apps liberados (tela nativa)'),
        ),
    ]
