# Generated by Django 5.2.7 on 2026-07-31 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0143_kioskdevice_permite_limpar_apps_terceiros'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeparacaoItemAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arquivo', models.FileField(upload_to='separacao/nf/%Y/%m/', verbose_name='Arquivo')),
                ('descricao', models.CharField(blank=True, default='', max_length=200, verbose_name='Descrição')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizador', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criador', to=settings.AUTH_USER_MODEL)),
                ('separacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos_nf', to='ProjetoEstoque.separacaoitem', verbose_name='Item em remessa')),
            ],
            options={
                'verbose_name': 'Nota Fiscal da Remessa',
                'verbose_name_plural': 'Notas Fiscais da Remessa',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
