# Generated by Django 5.2.7 on 2026-08-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0144_adiciona_separacao_item_anexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventiva',
            name='data_reativacao',
            field=models.DateField(blank=True, null=True, verbose_name='Última reativação do equipamento'),
        ),
    ]
