# Generated by Django 5.2.7 on 2026-08-25 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0154_backfill_itempadraodatasul_busca_fts'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicaoitem',
            name='numero_nf',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Número da NF'),
        ),
        migrations.AddField(
            model_name='requisicaoitem',
            name='valor_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Unitário (recebimento)'),
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('enviada_aprovacao', 'Enviada para Aprovação'), ('aprovada', 'Aprovada'), ('nao_aprovada', 'Não Aprovada'), ('pausada', 'Pausada'), ('com_erro', 'Com Erro'), ('cancelada', 'Cancelada')], db_index=True, default='rascunho', max_length=20),
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='status_anterior_pausa',
            field=models.CharField(blank=True, choices=[('rascunho', 'Rascunho'), ('enviada_aprovacao', 'Enviada para Aprovação'), ('aprovada', 'Aprovada'), ('nao_aprovada', 'Não Aprovada'), ('pausada', 'Pausada'), ('com_erro', 'Com Erro'), ('cancelada', 'Cancelada')], max_length=20, null=True, verbose_name='Status antes de pausar'),
        ),
    ]
