# Generated by Django 5.2.7 on 2026-09-06 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0156_backfill_status_solicitada_removida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicaoitem',
            name='item_vinculado',
            field=models.ForeignKey(blank=True, help_text='Vincula a um item de consumo já cadastrado (com ou sem estoque ainda) — mostra a quantidade disponível e permite dar entrada real ao receber a compra. Deixe em branco para cadastro livre.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicoes_kanban', to='ProjetoEstoque.item', verbose_name='Item / Equipamento (opcional)'),
        ),
    ]
