# Generated by Django 5.2.7 on 2026-09-06 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0157_alter_requisicaoitem_item_vinculado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LicencaOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('produto', models.CharField(help_text='Ex.: Office Home and Business 2016', max_length=160, verbose_name='Produto')),
                ('chave_produto', models.CharField(db_index=True, max_length=100, verbose_name='Chave / Serial')),
                ('status', models.CharField(choices=[('ok', 'OK'), ('problema', 'Com Problema'), ('expirada', 'Expirada'), ('cancelada', 'Cancelada')], default='ok', max_length=20, verbose_name='Status')),
                ('conta_vinculada', models.CharField(blank=True, max_length=150, verbose_name='Conta / E-mail de ativação')),
                ('id_dell', models.CharField(blank=True, help_text='Service Tag / identificador do fabricante, quando aplicável.', max_length=60, verbose_name='ID Principal Dell')),
                ('data_licenca', models.DateField(blank=True, null=True, verbose_name='Data da Licença')),
                ('estacao_importada', models.CharField(blank=True, help_text="Nome da estação como veio da planilha de origem — usado para localizar o equipamento na importação. O vínculo oficial é o campo 'Equipamento' abaixo.", max_length=100, verbose_name='Estação (planilha)')),
                ('usuario_vinculado', models.CharField(blank=True, max_length=100, verbose_name='Usuário vinculado à máquina')),
                ('observacao', models.TextField(blank=True, null=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizador', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criador', to=settings.AUTH_USER_MODEL)),
                ('item', models.OneToOneField(blank=True, help_text='Notebook/desktop do estoque a que esta licença pertence. Deixe em branco para manter a licença sem uso (em estoque).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licenca_office', to='ProjetoEstoque.item', verbose_name='Equipamento vinculado')),
            ],
            options={
                'verbose_name': 'Licença Office (por equipamento)',
                'verbose_name_plural': 'Licenças Office (por equipamento)',
                'ordering': ['produto', 'chave_produto'],
                'indexes': [models.Index(fields=['chave_produto'], name='ProjetoEsto_chave_p_241eb0_idx'), models.Index(fields=['status'], name='ProjetoEsto_status_d96c46_idx')],
            },
        ),
    ]
