# Generated by Django 5.2.7 on 2026-09-06 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0158_licencaoffice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilParceiroLicenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True, help_text='Desmarque para suspender o acesso sem excluir o usuário.')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizador', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criador', to=settings.AUTH_USER_MODEL)),
                ('parceiro', models.ForeignKey(help_text='Empresa externa com acesso ao Portal de Licenças Office (ex.: Routerlink).', on_delete=django.db.models.deletion.CASCADE, related_name='perfis_parceiro_licenca', to='ProjetoEstoque.fornecedor', verbose_name='Empresa parceira')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_parceiro_licenca', to=settings.AUTH_USER_MODEL, verbose_name='Usuário de acesso')),
            ],
            options={
                'verbose_name': 'Perfil de Parceiro de Licenças',
                'verbose_name_plural': 'Perfis de Parceiros de Licenças',
            },
        ),
    ]
