# Generated by Django 5.2.7 on 2026-09-21 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def encerrar_comandos_legados(apps, schema_editor):
    """Fecha os comandos que ficaram abertos antes da v1.8.0 do app.

    Até a v1.7.2 o app lia `comandos` e descartava — tudo ficou parado em
    pendente/entregue. A partir desta versão o servidor REENTREGA os abertos até
    o ACK; sem este fechamento, um aparelho recém-atualizado executaria na hora
    um "bloquear" pedido semanas atrás. Nada aqui foi executado de fato, então o
    status honesto é `expirado`.
    """
    KioskComando = apps.get_model('ProjetoEstoque', 'KioskComando')
    KioskComando.objects.filter(status__in=['pendente', 'entregue']).update(
        status='expirado',
        detalhe='Encerrado na atualização do servidor: o app anterior à v1.8.0 descartava comandos remotos.',
        finalizado_em=timezone.now(),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0160_grupo_parceiro_licenca'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kioskcomando',
            options={'ordering': ['-criado_em'], 'permissions': [('reiniciar_quiosque_remoto', 'Pode reiniciar aparelhos do quiosque remotamente')], 'verbose_name': 'Comando de Quiosque', 'verbose_name_plural': 'Comandos de Quiosque'},
        ),
        migrations.AddField(
            model_name='kioskcomando',
            name='app_versao',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Versão do app no ACK'),
        ),
        migrations.AddField(
            model_name='kioskcomando',
            name='executado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Executado em (no aparelho)'),
        ),
        migrations.AddField(
            model_name='kioskcomando',
            name='expira_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expira em'),
        ),
        migrations.AddField(
            model_name='kioskdevice',
            name='apps_abertos',
            field=models.JSONField(blank=True, default=list, verbose_name='Apps abertos (último check-in)'),
        ),
        migrations.AlterField(
            model_name='kioskcomando',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kiosk_comandos', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por'),
        ),
        migrations.AlterField(
            model_name='kioskcomando',
            name='detalhe',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='kioskcomando',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('entregue', 'Entregue'), ('executado', 'Executado'), ('falhou', 'Falhou'), ('nao_suportado', 'Não suportado'), ('expirado', 'Expirado')], db_index=True, default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='kioskcomando',
            name='tipo',
            field=models.CharField(choices=[('sincronizar_config', 'Sincronizar configuração'), ('reenviar_inventario', 'Reenviar inventário de apps'), ('exibir_mensagem', 'Exibir mensagem'), ('fechar_apps', 'Fechar apps'), ('limpar_cache', 'Limpar cache do app'), ('bloquear_tela', 'Bloquear tela'), ('reiniciar', 'Reiniciar aparelho'), ('reativar_quiosque', 'Reativar quiosque'), ('bloquear', 'Bloquear dispositivo (legado)'), ('desbloquear', 'Desbloquear dispositivo (legado)'), ('mensagem', 'Exibir mensagem (legado)'), ('atualizar_config', 'Atualizar configuração (legado)'), ('reiniciar_app', 'Reiniciar aplicativo (legado)')], max_length=40),
        ),
        migrations.RunPython(encerrar_comandos_legados, migrations.RunPython.noop),
    ]
