# Generated by Django 5.2.7 on 2026-09-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0161_kiosk_comandos_remotos_v18'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kioskcomando',
            options={'ordering': ['-criado_em'], 'permissions': [('reiniciar_quiosque_remoto', 'Pode reiniciar aparelhos do quiosque remotamente'), ('sair_quiosque_remoto', 'Pode tirar aparelhos do quiosque remotamente')], 'verbose_name': 'Comando de Quiosque', 'verbose_name_plural': 'Comandos de Quiosque'},
        ),
        migrations.AddField(
            model_name='kioskdevice',
            name='permite_notificacoes',
            field=models.BooleanField(default=False, verbose_name='Permite notificações (barra de status + bandeja)'),
        ),
        migrations.AlterField(
            model_name='kioskcomando',
            name='tipo',
            field=models.CharField(choices=[('sincronizar_config', 'Sincronizar configuração'), ('reenviar_inventario', 'Reenviar inventário de apps'), ('exibir_mensagem', 'Exibir mensagem'), ('fechar_apps', 'Fechar apps'), ('limpar_cache', 'Limpar cache do app'), ('bloquear_tela', 'Bloquear tela'), ('desbloquear', 'Desbloquear tela'), ('reiniciar', 'Reiniciar aparelho'), ('reiniciar_app', 'Reiniciar aplicativo'), ('reativar_quiosque', 'Reativar quiosque'), ('sair_quiosque', 'Sair do quiosque'), ('bloquear', 'Bloquear dispositivo (legado)'), ('mensagem', 'Exibir mensagem (legado)'), ('atualizar_config', 'Atualizar configuração (legado)')], max_length=40),
        ),
    ]
