# Generated by Django 5.2.7 on 2026-09-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0162_alter_kioskcomando_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='area_administrativa',
            field=models.BooleanField(default=False, help_text='Colaboradores de área administrativa costumam receber licenças de software no cadastro.', verbose_name='Área administrativa'),
        ),
    ]
