# Generated by Django 5.2.7 on 2026-09-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0163_usuario_area_administrativa'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilparceirolicenca',
            name='pode_ver_colaboradores',
            field=models.BooleanField(default=False, help_text='Quando ativo, este parceiro também enxerga a lista de colaboradores (nome, e-mail, função, centro de custo e localidade — sem dados sensíveis de RH) no Portal de Licenças. Desligado por padrão: cada parceiro só ganha essa visão se o TI liberar explicitamente.', verbose_name='Pode ver colaboradores'),
        ),
    ]
