# Generated by Django 5.2.7 on 2026-09-30 16:55

from django.db import migrations, models


# Mapeia o texto livre que o app já manda em `rede` (hoje só "wifi" e "none")
# para o `rede_tipo` normalizado, no histórico JÁ gravado. Sem este backfill, os
# ~45 mil check-ins existentes ficariam com rede_tipo vazio e o mapa de rota não
# saberia classificar o transporte de nenhum ponto passado — perdendo de graça o
# histórico de conectividade que já está no banco.
_TIPO_POR_REDE = {
    'wifi': 'wifi', 'wi-fi': 'wifi', 'wlan': 'wifi',
    'cellular': 'movel', 'celular': 'movel', 'movel': 'movel', 'móvel': 'movel', 'mobile': 'movel',
    'ethernet': 'ethernet', 'eth': 'ethernet', 'lan': 'ethernet',
    'none': 'nenhuma', 'nenhuma': 'nenhuma', 'offline': 'nenhuma',
}


def backfill_rede_tipo(apps, schema_editor):
    KioskCheckin = apps.get_model('ProjetoEstoque', 'KioskCheckin')
    for rede, tipo in _TIPO_POR_REDE.items():
        KioskCheckin.objects.filter(rede__iexact=rede, rede_tipo='').update(rede_tipo=tipo)


def desfazer_backfill(apps, schema_editor):
    """Reversão: o campo inteiro é removido no rollback do AddField, então não há
    o que desfazer aqui — existe só para a migration ser reversível."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0164_perfilparceirolicenca_pode_ver_colaboradores'),
    ]

    operations = [
        migrations.AddField(
            model_name='kioskcheckin',
            name='movel_geracao',
            field=models.CharField(blank=True, default='', max_length=6, verbose_name='Geração móvel (2g/3g/4g/5g)'),
        ),
        migrations.AddField(
            model_name='kioskcheckin',
            name='movel_nivel',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nível de sinal móvel (0-4)'),
        ),
        migrations.AddField(
            model_name='kioskcheckin',
            name='movel_operadora',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Operadora'),
        ),
        migrations.AddField(
            model_name='kioskcheckin',
            name='movel_rssi_dbm',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sinal móvel (dBm)'),
        ),
        migrations.AddField(
            model_name='kioskcheckin',
            name='movel_tecnologia',
            field=models.CharField(blank=True, default='', max_length=24, verbose_name='Tecnologia móvel (crua)'),
        ),
        migrations.AddField(
            model_name='kioskcheckin',
            name='rede_tipo',
            field=models.CharField(blank=True, db_index=True, default='', max_length=12, verbose_name='Tipo de rede'),
        ),
        migrations.AddField(
            model_name='kioskdevice',
            name='telemetria_movel',
            field=models.BooleanField(default=False, verbose_name='Telemetria de rede móvel (3G/4G/5G)'),
        ),
        migrations.AddField(
            model_name='kioskdevice',
            name='ultima_movel_geracao',
            field=models.CharField(blank=True, default='', max_length=6, verbose_name='Geração móvel (última leitura)'),
        ),
        migrations.AddField(
            model_name='kioskdevice',
            name='ultima_movel_operadora',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Operadora (última leitura)'),
        ),
        migrations.AddField(
            model_name='kioskdevice',
            name='ultima_rede_tipo',
            field=models.CharField(blank=True, default='', max_length=12, verbose_name='Tipo de rede (última leitura)'),
        ),
        migrations.AddField(
            model_name='kioskdevice',
            name='ultimo_sinal_dbm',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sinal em dBm (última leitura)'),
        ),
        migrations.AddField(
            model_name='kioskdevice',
            name='ultimo_sinal_nivel',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nível de sinal 0-4 (última leitura)'),
        ),
        migrations.RunPython(backfill_rede_tipo, desfazer_backfill),
    ]
