# Generated by Django 5.2.7 on 2026-09-30 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoEstoque', '0165_kiosk_telemetria_rede_movel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreventivaFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('imagem', models.ImageField(upload_to='preventivas/%Y/%m/', verbose_name='Imagem')),
                ('momento', models.CharField(choices=[('antes', 'Antes'), ('depois', 'Depois'), ('ambos', 'Antes e depois')], db_index=True, default='antes', max_length=10, verbose_name='Momento')),
                ('legenda', models.CharField(blank=True, default='', help_text='Descrição opcional do que a foto mostra.', max_length=200, verbose_name='Legenda')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('origem_legado', models.CharField(blank=True, db_index=True, default='', max_length=40, verbose_name='Origem (campo legado)')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizador', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criador', to=settings.AUTH_USER_MODEL)),
                ('execucao', models.ForeignKey(blank=True, help_text='Vazio nas evidências anteriores ao histórico de execuções.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='ProjetoEstoque.preventivaexecucao', verbose_name='Execução')),
                ('preventiva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='ProjetoEstoque.preventiva', verbose_name='Preventiva')),
            ],
            options={
                'verbose_name': 'Foto de Preventiva',
                'verbose_name_plural': 'Fotos de Preventiva',
                'ordering': ['ordem', 'id'],
                'indexes': [models.Index(fields=['preventiva', 'momento'], name='ProjetoEsto_prevent_780d50_idx'), models.Index(fields=['execucao', 'ordem'], name='ProjetoEsto_execuca_c6a899_idx')],
            },
        ),
    ]
